### ISSUE TITLE
用这个库调用exopalyer播放音乐时，同时用exomedia播放视频，无法同时播放音视频。

### ISSUE THREAD

**Issue by shenbengit** [lizixian18/MusicLibrary#10]
后播放的会暂停先播放的，有没有办法实现同时播放？

**Comment by lizixian18** [comment]
你需要同时播放音频和视频？无法播放时因为有一个音乐焦点的管理，如果你有这样的需求那我可以弄一个开关吧。

**Comment by shenbengit** [comment]
如果你有空的话，帮我弄一下吧，我需要，因为我要把放的视频没有声音。如果没空，也可以告诉我该如何处理。谢谢。

**Comment by lizixian18** [comment]
有任何问题都可以反馈，我都会去处理的，这个我现在就弄。

**Comment by shenbengit** [comment]
非常感谢！！！

**Comment by lizixian18** [comment]
因为放弃焦点管理会有些问题，比如接电话，打电话，点其他应用的视频或者音乐的时候都会混播，所以我得想想如何管理这些东西，得问清楚你的需求是这些情况都可以自动暂停还是全部都可以混播？

**Comment by lizixian18** [comment]
代码提交了，你急的可以先下载源码同过library的方式引用看看行不行，暂时没那么快发新版。

**Comment by shenbengit** [comment]
好的，非常感谢！
