### ISSUE TITLE
哥们，你这个库是如何实现根据不同的链接播放不同的音乐列表的

### ISSUE THREAD

**Issue by mrchenmo** [lizixian18/MusicLibrary#101]
我用的是原生的ump，改了好多东西，还是有问题，我都不想改了

**Comment by EspoirX** [comment]
根据不同的链接播放不同的音乐列表是什么意思

**Comment by mrchenmo** [comment]
> 根据不同的链接播放不同的音乐列表是什么意思

就是从不同的地方进去取不同的链接然后播放不同的音乐列表

**Comment by EspoirX** [comment]
替换掉不就好了

**Comment by mrchenmo** [comment]
> 替换掉不就好了

要是这样呢：正在播放的列表依旧播放，进入到别的列表

**Comment by EspoirX** [comment]
点播放的时候再替换，你可以看看我的代码

**Comment by mrchenmo** [comment]
> 点播放的时候再替换，你可以看看我的代码

之前没看到你这个库，我就用原生的ump改了好久，我看看吧再

**Comment by EspoirX** [comment]
ump。。其实是啥，看不懂缩写。。

**Comment by mrchenmo** [comment]
> ump。。其实是啥，看不懂缩写。。

android-UniversalMusicPlayer 。。。。。。。你这个库的核心也是参考了它吧

**Comment by EspoirX** [comment]
哦哦，参考了，UniversalMusicPlayer 还是不错的
