### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by Dkoran** [lizixian18/MusicLibrary#102]
I currently want to create offline mode where by users can ad songs or music to their library immediately they add to their library they can play those songs in offline mode.
How can I achieve that.

**Comment by EspoirX** [comment]
you can set cache in application like this ：
```
//set cache
String destFileDir = Environment.getExternalStorageDirectory().getAbsolutePath() + "/ExoCacheDir";
ExoDownload.getInstance().setOpenCache(true); //open cache
ExoDownload.getInstance().setShowNotificationWhenDownload(false);
ExoDownload.getInstance().setCacheDestFileDir(destFileDir); //set cache dir
```
and the songs will be downloaded to a local folder

**Comment by EspoirX** [comment]
Please use the latest version, the master branch is no longer maintained

**Comment by Dkoran** [comment]
okay but is it going to only download and cache the the songs I played or it is going to download the songs user have added to play in the library

**Comment by EspoirX** [comment]
What features do you need to process the song cache?

**Comment by Dkoran** [comment]
I have music streaming platform which has 4 tabs, Discover, trending, new music and videos,
I am adding an add button whereby user can click and add songs to their Library, immediately they click on that, they can play the songs in the Library offline

**Comment by EspoirX** [comment]
No problem, as long as you set the cache, it will be downloaded automatically when playing music, and you will not need the network when you play it again next time.

**Comment by Dkoran** [comment]
okay, So I should set it at the library Activity and also How can I make users clear or remove songs they don't want again

**Comment by Dkoran** [comment]
Hi please Can you help me with this, I have created add to my library where individual selected songs are stored and kept but my boss wants me to add a download button to it where by when the selected song is added and the user goes to the library and clicks on a download button the song should download and stored for offline play, please how can I trigger the download button to work with your library to able to download it
