### ISSUE TITLE
网络音频播放和状态监听

### ISSUE THREAD

**Issue by Bruce8hou** [lizixian18/MusicLibrary#104]

**Comment by Bruce8hou** [comment]
1.当播放的网络音频很短的时候（1s左右）出现没有声音 
2.我在两个APP中都用到了StarrySky，都addPlayerEventListener了，如果我把两个APP同时打开出现了监听消息互相影响的BUG  有没有什么办法区别开 不互相影响呢

**Comment by EspoirX** [comment]
互相影响具体是指什么

**Comment by EspoirX** [comment]
把服务的 exported 设为 false 试试看行不行

**Comment by Bruce8hou** [comment]
比如在播放音频的时候 后台一个app给了一个音频停止指令，我的app的音频播放也停止了，能不能分离开呢  或者控制器一直在我的app里

**Comment by EspoirX** [comment]
第一种方法，把服务的 exported 设为 false ，如果还不行就给服务加个权限，试试看？

**Comment by Bruce8hou** [comment]
能否告知一下具体哪个代码位置呢

**Comment by Bruce8hou** [comment]
第一方法会造成闪退，能否说一下第二种方法的具体操作方法呢？

**Comment by Bruce8hou** [comment]
mExoPlayer.setAudioAttributes(audioAttributes, false); 修改这里可以搞定

**Comment by EspoirX** [comment]
true的意思是让exoplayer自动管理音频焦点
