### ISSUE TITLE
How can I trigger before play music

### ISSUE THREAD

**Issue by cuong95nddev** [lizixian18/MusicLibrary#108]
Thank for a good library.

I am in a case:
I need to call a service to get song url for every one of songs before can play it.
So I dont know how to handle it with your library. (May be a hook or some thing I can trigger it to call the service and play it again after finish?)

**Comment by EspoirX** [comment]
This feature is currently unavailable, which is your business function, but for now you can request to call the playback feature, I am trying to integrate it into the library.

**Comment by cuong95nddev** [comment]
That sounds good to hear that.
Thank a lot.

**Comment by EspoirX** [comment]
I think to use AOP is the best way to solve your problem.

**Comment by EspoirX** [comment]
https://github.com/EspoirX/StarrySky/blob/StarrySkyJava/readme/%E6%92%AD%E6%94%BE%E5%89%8D%E9%9C%80%E6%B1%82%E5%85%88%E8%AF%B7%E6%B1%82%E6%8E%A5%E5%8F%A3%E8%8E%B7%E5%8F%96url%E6%97%B6%E7%9A%84%E5%A4%84%E7%90%86%E6%96%B9%E6%B3%95.md

**Comment by cuong95nddev** [comment]
> https://github.com/EspoirX/StarrySky/blob/StarrySkyJava/readme/%E6%92%AD%E6%94%BE%E5%89%8D%E9%9C%80%E6%B1%82%E5%85%88%E8%AF%B7%E6%B1%82%E6%8E%A5%E5%8F%A3%E8%8E%B7%E5%8F%96url%E6%97%B6%E7%9A%84%E5%A4%84%E7%90%86%E6%96%B9%E6%B3%95.md

Thank you verry much for your good job. 
The above solution it seem just works for UI thread.
In case the music run on background, how can we add a "DelayAction" ?

Thanks

**Comment by EspoirX** [comment]
1. Can be used with version 2.1.9
2. The general step is to request your url through your network request framework in the doValid method, then assemble SongInfo in the callback to use it, and then call the doCall method. Where do you need to use sub-threads?
3. I haven't had time to translate the document into English. If you don't understand it, please ask, thank you.

**Comment by cuong95nddev** [comment]
![image](https://user-images.githubusercontent.com/13380834/57296140-6d540780-70f6-11e9-8401-cf2903236f45.png)

Iam not sure it can solve my problem.
Here is my case.
Thanks.

**Comment by EspoirX** [comment]
Can you show me your code so that I can find another way to solve your problem.

**Comment by cuong95nddev** [comment]
Sure, here is my project.
You can take a look on it https://github.com/anhbinhvodanh/Music/invitations
Thanks.
