### ISSUE TITLE
播放问题

### ISSUE THREAD

**Issue by HQLIE2018** [lizixian18/MusicLibrary#109]
怎样才能在播完一首曲目后不再播放下一首？想实现的是播完一首后就停止，需要播放时，用户再去播放列表那里点击需要播放的曲目

**Comment by EspoirX** [comment]
每次只传一首歌

**Comment by HQLIE2018** [comment]
现在我是通过MusicManager.getInstance().playMusicByInfo(mSongInfo);这种方式播放音频的，每次传的参数都是一个新的对象，但是当传了两首不同的曲目时，播完当前曲目后会反顺序播放上一首曲目，这要怎么处理，是不是我的做法不对？

**Comment by EspoirX** [comment]
你用这个方法

playMusic(List<SongInfo> songInfos, int index)


每次 list 只有一首歌，index 传 0 试试
