### ISSUE TITLE
锁屏问题

### ISSUE THREAD

**Issue by HQLIE2018** [lizixian18/MusicLibrary#110]
怎么样才能关闭锁屏时的显示呀

**Comment by HQLIE2018** [comment]
这个比较急，麻烦回答一下

**Comment by EspoirX** [comment]
服务里面有一句mediaSession.setActive(true);的，你把它设为false即可

**Comment by HQLIE2018** [comment]
MediaSessionConnection这个类吗？

**Comment by EspoirX** [comment]
服务啊，musicservice

**Comment by HQLIE2018** [comment]
好的，谢谢！我看了一下，不知道你有没有暴露方法出来，我没找到，我是通过修改源码去关闭的

**Comment by EspoirX** [comment]
暂时没有暴露。因为做的时候没想到这个，后面会加上的

**Comment by HQLIE2018** [comment]
好的，那我暂时通过修改源码去实现了，谢谢！
