### ISSUE TITLE
播放格式

### ISSUE THREAD

**Issue by HQLIE2018** [lizixian18/MusicLibrary#111]
你好，请问这个库支持什么音乐格式呀？

**Comment by EspoirX** [comment]
你需要什么格式

**Comment by HQLIE2018** [comment]
我想了解一下这个库支持的音乐格式

**Comment by EspoirX** [comment]
readme有写

**Comment by HQLIE2018** [comment]
不好意思，我找了一下，没找到，请问是在readme里面哪个文件呀

**Comment by EspoirX** [comment]
支持普通音频格式和 DASH, SmoothStreaming, HLS，rtmp 等流式音频

**Comment by HQLIE2018** [comment]
支持AAC格式吧

**Comment by EspoirX** [comment]
支持吧，你试试

**Comment by HQLIE2018** [comment]
AAC是可以的，但不支持FLAC

**Comment by HQLIE2018** [comment]
一般报ExoPlayer error Unable to connect to http://file.service.beta.2239.com/files/2019/3/27/20190327113727-XPwGaZ.wav这个错什么原因呀

**Comment by EspoirX** [comment]
flac 已经支持了
