### ISSUE TITLE
连接异常

### ISSUE THREAD

**Issue by HQLIE2018** [lizixian18/MusicLibrary#113]
java.lang.IllegalStateException
connect() called while neither disconnecting nor disconnected (state=CONNECT_STATE_SUSPENDED)
com.lzx.starrysky.manager.MediaSessionConnection.connect(MediaSessionConnection.java:124)
对这个异常不是特别理解，看代码已经做了是否已经断开连接的判断，但还是会出现这个状态的异常

**Comment by EspoirX** [comment]
能重现吗，重现的时候debug一下看看？

**Comment by HQLIE2018** [comment]
暂时我也无法重现，是用户那边反馈的，我也在尝试让它重现

**Comment by HQLIE2018** [comment]
出现这种情况的原因大概是程序进入后台比较久，回调了onServiceDisconnected这个方法，状态改变为CONNECT_STATE_SUSPENDED，实际上mediaBrowser并没有断开连接，麻烦你看看有没有什么可以优化的地方

**Comment by EspoirX** [comment]
看源码发现 onServiceDisconnected 会回调 onConnectionSuspended，所以在这个方法里面做 disconnect 操作应该就好了
