### ISSUE TITLE
能不能一次只播放一首播放一遍，不自动播放列表中其他音乐

### ISSUE THREAD

**Issue by wfs3006** [lizixian18/MusicLibrary#114]
![微信截图_20190409152558](https://user-images.githubusercontent.com/4847216/55781047-da668400-5adb-11e9-82d1-73bc2caa980d.png)

需求是图中点击那个读音，播放一次，现在把多个读音设置进播放列表
MusicProvider.getInstance().setSongInfos(songInfoList);
点击的时候
MusicManager.getInstance().playMusicByIndex(position);
会自动播放其他音频，有解决方案吗，

**Comment by wfs3006** [comment]
建议设置个开关，设置是否自动播放

**Comment by EspoirX** [comment]
List<SongInfo> songInfoList = new ArrayList<>();
songInfoList.add(new SongInfo);
MusicProvider.getInstance().setSongInfos(songInfoList);
每次播放list里面都只有一首歌就行了
