### ISSUE TITLE
获取正在播放音乐信息存在bug

### ISSUE THREAD

**Issue by LoveqLRC** [lizixian18/MusicLibrary#118]
当前获取正在播放信息是通过
```
 MediaControllerCompat.Callback 
```
中`onMetadataChanged`方法更新正在播放的`nowPlaying`，
但是这样会存在一个问题，当` MediaSessionConnection.getInstance().disconnect()`的时候去取消监听`MediaControllerCompat.Callback `，从而导致第二次从新连接获取正在播放的`nowPlaying`，会存在获取上一次的播放信息的情况。

**Comment by LoveqLRC** [comment]
建议在连接的时候再刷一次`nowPlaying`的信息
```
MediaBrowserCompat.ConnectionCallback
```
通过`mediaController`更新`nowPlaying`

**Comment by EspoirX** [comment]
可以描述一下你的使用场景吗，你说断开链接后点击下一首，然后重新链接再获取播放信息的意思吗

**Comment by LoveqLRC** [comment]
你可以参考一下这个[android-UniversalMusicPlayer-BaseActivity](https://github.com/googlesamples/android-UniversalMusicPlayer/blob/v1/mobile/src/main/java/com/example/android/uamp/ui/BaseActivity.java#L150)。
重现的步骤：
`AActivity`

```
override fun onStart() {
 MediaSessionConnection.getInstance().connect()
}
override fun onStop() {
        super.onStop()
        MediaSessionConnection.getInstance().disconnect()
    }
```
正在播放B song，然后退出程序，后台服务继续跑，B song 播放结束，切换到C song, 现在重新打开程序，因为你正在播放的`nowPlaying `是只有切换的时候才更新的，而程序退出后，监听停止了，所以第二次链接上获取的`nowPlaying `还是B song

**Comment by fenggit** [comment]
> 当前获取正在播放信息是通过
> 
> ```
>  MediaControllerCompat.Callback 
> ```
> 
> 中`onMetadataChanged`方法更新正在播放的`nowPlaying`，
> 但是这样会存在一个问题，当` MediaSessionConnection.getInstance().disconnect()`的时候去取消监听`MediaControllerCompat.Callback `，从而导致第二次从新连接获取正在播放的`nowPlaying`，会存在获取上一次的播放信息的情况。

请问，你是怎么解决的？

**Comment by LoveqLRC** [comment]
@fenggit 
建议在连接的时候再刷一次`nowPlaying`的信息
```
MediaBrowserCompat.ConnectionCallback
```
通过`mediaController`更新`nowPlaying`

**Comment by fenggit** [comment]
> @fenggit
> 建议在连接的时候再刷一次`nowPlaying`的信息
> 
> ```
> MediaBrowserCompat.ConnectionCallback
> ```
> 
> 通过`mediaController`更新`nowPlaying`

感谢回复，方便加微信吗？微信号：hefengs
我现在是没有断开连接服务

**Comment by fenggit** [comment]
> @fenggit
> 建议在连接的时候再刷一次`nowPlaying`的信息
> 
> ```
> MediaBrowserCompat.ConnectionCallback
> ```
> 
> 通过`mediaController`更新`nowPlaying`

感谢回复，方便加微信吗？微信号：hefengs
我现在是没有断开连接服务

**Comment by fenggit** [comment]
> @fenggit
> 建议在连接的时候再刷一次`nowPlaying`的信息
> 
> ```
> MediaBrowserCompat.ConnectionCallback
> ```
> 
> 通过`mediaController`更新`nowPlaying`

连接的时候刷新不行的，我们还有悬浮窗口

**Comment by LoveqLRC** [comment]
## MediaSessionConnection

```
   /**
     * 连接回调
     */
    private class MediaBrowserConnectionCallback extends MediaBrowserCompat.ConnectionCallback {
        /**
         * 已连接上
         */
        @Override
        public void onConnected() {
            super.onConnected();
            try {
                mediaController = new MediaControllerCompat(sContext, mediaBrowser.getSessionToken());
                mediaController.registerCallback(mMediaControllerCallback);
                MediaMetadataCompat metadata = mediaController.getMetadata();
                nowPlaying = metadata != null ? metadata : NOTHING_PLAYING;
                PlaybackStateCompat state = mediaController.getPlaybackState();
                playbackState = state != null ? state : EMPTY_PLAYBACK_STATE;

                transportControls = mediaController.getTransportControls();
                rootMediaId = mediaBrowser.getRoot();
                isConnected = true;
                if (!mConnectListenerList.isEmpty()) {
                    for (OnConnectListener mConnectListener : mConnectListenerList) {
                        mConnectListener.onConnected();
                    }
                }
            } catch (RemoteException e) {
                e.printStackTrace();
            }
        }

        @Override
        public void onConnectionSuspended() {
            super.onConnectionSuspended();
            disconnect();
            isConnected = false;
        }

        @Override
        public void onConnectionFailed() {
            super.onConnectionFailed();
            isConnected = false;
        }
    }
```

@fenggit

**Comment by fenggit** [comment]
@LoveqLRC thanks

**Comment by fenggit** [comment]
> > 当前获取正在播放信息是通过
> > ```
> >  MediaControllerCompat.Callback 
> > ```
> > 
> > 
> > 中`onMetadataChanged`方法更新正在播放的`nowPlaying`，
> > 但是这样会存在一个问题，当` MediaSessionConnection.getInstance().disconnect()`的时候去取消监听`MediaControllerCompat.Callback `，从而导致第二次从新连接获取正在播放的`nowPlaying`，会存在获取上一次的播放信息的情况。
> 
> 请问，你是怎么解决的？

我没有断开连接
