### ISSUE TITLE
关于 MediaSessionConnection的疑问

### ISSUE THREAD

**Issue by LoveqLRC** [lizixian18/MusicLibrary#119]
在AActivity和BActivity中
```
override fun onStart() {
 MediaSessionConnection.getInstance().connect()
}
override fun onStop() {
        super.onStop()
        MediaSessionConnection.getInstance().disconnect()
    }
```
AActivity启动BActivity，然后关闭BActivity，返回AActivity，这时候会存在问题，因为生命周期的流程是
启动BActivity 的生命周期流程是 onStart(AActivity) ->onStart(BActivity)  ->onStop(AActivity) 这里会把之前的连接断开，
返回AActivity的生命周期流程是  onStart(AActivity) -> onStop(BActivity)  这里会把之前的连接断开。

**Comment by EspoirX** [comment]
其实我建议如果不是有特殊要求的话，不用每个界面都调用 connect 和 disconnect，disconnect 只在你 app 不需要音频的时候调一下就好了

**Comment by LoveqLRC** [comment]
嗯，但是我觉得这样缺少了灵活性，每个页面自己管理mediaBrowser，我感觉会更加灵活。

**Comment by LoveqLRC** [comment]
我现在有两个Activity，那么什么时候disconnect 恰当？

**Comment by CB2Git** [comment]
不用断开连接啊，你不用的时候断开不就行了  音乐播放器本来就不能和ui关联在一起，除非你不想要后台播放

**Comment by EspoirX** [comment]
对的，不用断开得那么频繁

**Comment by LoveqLRC** [comment]
整个应用现在有两个Activity，不断开，那么就是一直保持连接，那么connect的回调就不会走，那么每次获取的状态有可能不正确，具体见  #118  ，这是一种情况。
第二情况是，通过`Notification`点击进入`BActivty`，是先经过`AActivity`的，这个做法和谷歌例子那个一样。这里会导致`AActivity`还没连接上就进入`BActivity`了，后续就会引起一连串问题。

**Comment by ruanbaojun1105** [comment]
牛弹琴
