### ISSUE TITLE
关于播放模式的API

### ISSUE THREAD

**Issue by leavesCZY** [lizixian18/MusicLibrary#121]
请问 setRepeatMode 和 setShuffleMode 两者的关联是什么呢？为什么都有“顺序播放”这个概念

**Comment by EspoirX** [comment]
setRepeatMode 是设置播放模式，对应着 
PlaybackStateCompat.REPEAT_MODE_NONE  
PlaybackStateCompat.REPEAT_MODE_ONE  
PlaybackStateCompat.REPEAT_MODE_ALL  
PlaybackStateCompatExt.SINGLE_MODE_ONE 
这四个变量。

setShuffleMode 是乱序模式，对应着
PlaybackStateCompat.SHUFFLE_MODE_NON
PlaybackStateCompat.SHUFFLE_MODE_ALL
这两个变量，乱序的意思是打乱播放列表顺序，所以顺序播放就是恢复成正常顺序。
对应的解释可以查看这些变量对应的注释。
