### ISSUE TITLE
MusicService存在被杀死的情况

### ISSUE THREAD

**Issue by LoveqLRC** [lizixian18/MusicLibrary#122]
我同时打开了网易云音乐和[android-UniversalMusicPlayer](https://github.com/googlesamples/android-UniversalMusicPlayer)(v1分支)进行对比，但是用我们的库就是会存在被杀死的情况，当时正在播放(比较少触发，但是这个情况是存在的)，如何定位找到该问题，并解决它？有时候3、4分钟就挂了，有时候可以播放一个多小时，有时候没事，希望作者给点提示。

**Comment by palorotolo** [comment]
添加到了系统白名单吗？
