### ISSUE TITLE
添加需求（设置音量时，不能改变系统的媒体音量）

### ISSUE THREAD

**Issue by 121104115wyb** [lizixian18/MusicLibrary#128]
测试结果如下；手机的媒体音量取值为0-15；假设我设置的音量为7；然后调用                MusicManager.getInstance().setVolume();方法时，设置为1.0f时音量还是媒体音量的7这么大声音，只有当我手动调大（手机的音量加减键）音量时，声音才会增大，希望大佬添加一个api可以调整系统的媒体音量大小，目前为满足需求，我只能下载源码，修改了

**Comment by EspoirX** [comment]
你是说改手机本身的音量大小吗

**Comment by 121104115wyb** [comment]
是的，就是手机的媒体音量
