### ISSUE TITLE
control == null

### ISSUE THREAD

**Issue by Deepblue1996** [lizixian18/MusicLibrary#13]
control == null
无法正常使用

**Comment by lizixian18** [comment]
不会是服务没起来吧，你看看有没有:musiclibrary进程

**Comment by Deepblue1996** [comment]
![qq 20180423152736](https://user-images.githubusercontent.com/16926380/39112373-e1e1bed8-470a-11e8-9ebb-5673b6a6deeb.png)

**Comment by Deepblue1996** [comment]
有跑进去

**Comment by Deepblue1996** [comment]
我看看

**Comment by lizixian18** [comment]
你断点一下这里143行，看看ServiceConnection里面有没有赋值

**Comment by lizixian18** [comment]
好像真的有问题，我看看

**Comment by Deepblue1996** [comment]
![qq 20180423153905](https://user-images.githubusercontent.com/16926380/39112889-7d1b5ab6-470c-11e8-9359-11b4af1d48c9.png)
没有跑到

**Comment by lizixian18** [comment]
这么神奇吗，你再断下137行，看看有没有bindService

**Comment by Deepblue1996** [comment]
![qq 20180423154217](https://user-images.githubusercontent.com/16926380/39113044-ee87f434-470c-11e8-91a3-8c24a5aeeb61.png)

**Comment by lizixian18** [comment]
刚刚我在demo中试了一下，是没问题的。你这里很奇怪，它绑定了服务还不走 onServiceConnected 回调这么神奇

**Comment by Deepblue1996** [comment]
![qq 20180423154834](https://user-images.githubusercontent.com/16926380/39113278-cde80858-470d-11e8-9dbe-81a3d90d6c91.png)
我刚刚自己写了个服务是可以绑定回调的，是不是要AndroidManifest注册？

**Comment by lizixian18** [comment]
不需要自己注册，我里面都注册好了。
我觉得可以试试下面的做法：
第一个看看服务启动了没有，看看有没有musiclibrary进程。
第二个可以先clone代码，先用library的方式引用，方便调试问题所在
第三个，我是在[NiceMusic](https://github.com/lizixian18/NiceMusic)这个demo里面测试的，没重现到问题，你也可以看看

**Comment by Deepblue1996** [comment]
本地引用库，一样没回调，额(⊙﹏⊙)

**Comment by lizixian18** [comment]
擦，想不通啊

**Comment by Deepblue1996** [comment]
你的NiceMusic应该是用AndroidStudio3.0+开发的，我花了点功夫刚移植到AndroidStudio2.3，现在测试体体

**Comment by lizixian18** [comment]
现在都用3.0了吧，我用3.0.1的

**Comment by Deepblue1996** [comment]
用惯2.3.3，我个人不太喜欢3.0的调试器，还有一些项目都是2.3.3开发的，出问题麻烦，所以没用，不过我装了最新的as预览版

**Comment by Deepblue1996** [comment]
你的项目的确可以回调的，奇怪

**Comment by lizixian18** [comment]
不知道你是不是设置了什么其他东西影响到了……

**Comment by Deepblue1996** [comment]
吖，用不了

**Comment by Deepblue1996** [comment]
我刚刚开了一个新demo，也不可以，没有回调，你也试试创建一个新的demo，引用，然后application断init里面的回调

**Comment by lizixian18** [comment]
我创建一个试试

**Comment by Deepblue1996** [comment]
qq1023509177

**Comment by Deepblue1996** [comment]
27+, 需要额外引用
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:support-media-compat:27.1.1'
