### ISSUE TITLE
AAC格式的文件无法获取getDuration() 

### ISSUE THREAD

**Issue by HQLIE2018** [lizixian18/MusicLibrary#139]
AAC格式的文件无法获取getDuration() ，并且调用seeTo()这个方法时会重头播放

**Comment by windfone** [comment]
先调用 播放方法，再调用 seekTo 方法

**Comment by HQLIE2018** [comment]
> 先调用 播放方法，再调用 seekTo 方法

已经是处于播放的状态了

**Comment by EspoirX** [comment]
提供一首音频给我试试？

**Comment by HQLIE2018** [comment]
> 提供一首音频给我试试？

http://file.service.beta.2239.com/files/2019/10/28/20191028152843-LIYENr.aac

**Comment by EspoirX** [comment]
这首歌播放器获取到的时长是负数：-9223372036854775807，是一个不正常的值
1. 可能是这个音频有问题，可以换一首试试。
2. 这个库时长是通过播放器的 getDuration 获取的，可能这格式不支持这样获取时长
