### ISSUE TITLE
EspoirX大大,使用playMusicByInfo(info)时mMapHeadData不生效

### ISSUE THREAD

**Issue by OCTSJimmy** [lizixian18/MusicLibrary#148]
具体BUG表现是这样子的：
StarrySky.with().playMusicByInfo(info); 
这个方法是没法将 **SongInfo** 中的 _mMapHeadData_ 传给 **BaseMediaInfo** 中的 _mapHeadData_ 的。
只有 **updatePlayList(List<SongInfo>)** 或 **playMusic(List<SongInfo>, int)** 这两个方法才可以。
如图所示：

![StarrySkyBug-playMusicByInfo](https://user-images.githubusercontent.com/9329993/71436092-c674b800-2726-11ea-8bf8-879da5042552.png)

右侧的那个方法是playMusicByInfo(info)等update相关的以外的方法会调到的代码。
左侧的则为update相关的会调到的代码。
**注意左侧划红线部分做了赋值，右侧没有这个赋值，导致BaseMediaInfo的mapHeadData一直为null。**

望解决，非常感谢。

**Comment by EspoirX** [comment]
已更新。
