### ISSUE TITLE
播放网络音频

### ISSUE THREAD

**Issue by xiao349305433** [lizixian18/MusicLibrary#15]
SongInfo songInfo = new SongInfo();
songInfo.setSongId("Id"); 
songInfo.setSongUrl("http://zhangmenshiting.qianqian.com/data2/music/90fb2ed26f4e5fbd8efa4a7144758421/569080853/569080853.mp3?xcode=333db5ac3240bd1308a65907a49a17b0"); 
MusicManager.get().playMusicByInfo(songInfo);
我只传了id和url，为什么不能播放，还需要其他操作么，权限都有，Application里也添加了MusicLibrary

**Comment by lizixian18** [comment]
你这地址是不是失效了，试试这个地址 
```
http://sc1.111ttt.cn:8282/2018/1/03m/13/396131202421.m4a?tflag=1519095601&pin=6cd414115fdb9a950d827487b16b5f97#.mp3
```

**Comment by xiao349305433** [comment]
没有报错，
我直接在你的demo MusicLibray  里写的，加了Application和权限，是不是需要再加其他什么

**Comment by xiao349305433** [comment]
tv.setOnClickListener(new View.OnClickListener() 
 {
            @Override
            public void onClick(View view) {
                SongInfo songInfo=new SongInfo();
                songInfo.setSongId("123456");
                songInfo.setSongUrl("http://sc1.111ttt.cn:8282/2018/1/03m/13/396131202421.m4a?tflag=1519095601&pin=6cd414115fdb9a950d827487b16b5f97#.mp3");
                MusicManager.get().playMusicByInfo(songInfo);
            }
        });



    if (!BaseUtil.getCurProcessName(this).contains(":musicLibrary")) {
            MusicManager.get()
                    .setContext(this)
                    .init();
        }

 <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

就加了这么一点代码，还需要加其他的么

**Comment by lizixian18** [comment]
不用加什么，我也是在demo里面写的，就这样，你还是不行？：
![qq 20180426120852](https://user-images.githubusercontent.com/16240767/39285383-acaf85f0-494a-11e8-9e27-1306d3b86eba.png)

**Comment by lizixian18** [comment]
你可以断点一下playMusicByInfo方法

**Comment by xiao349305433** [comment]
嗯。。。还是不行，换了个手机也不行，有点弄不明白，能加个QQ么

**Comment by lizixian18** [comment]
可以，386707112

**Comment by lizixian18** [comment]
原因：自己写demo的时候忘记注册 Application 导致音频服务没启动，已解决。
