### ISSUE TITLE
如何拦截一首歌曲的播放

### ISSUE THREAD

**Issue by tdxtxt** [lizixian18/MusicLibrary#152]
我的播放列表中有部分内容需要付费才能播放，所以有没有在播放一首歌曲之前进行拦截判断的方法？

**Comment by EspoirX** [comment]
请参考这个文档 https://github.com/EspoirX/StarrySky/blob/StarrySkyJava/readme/%E6%92%AD%E6%94%BE%E5%89%8D%E9%9C%80%E6%B1%82%E5%85%88%E8%AF%B7%E6%B1%82%E6%8E%A5%E5%8F%A3%E8%8E%B7%E5%8F%96url%E6%97%B6%E7%9A%84%E5%A4%84%E7%90%86%E6%96%B9%E6%B3%95.md
