### ISSUE TITLE
INotification   stopNotification   java.lang.NullPointerException  

### ISSUE THREAD

**Issue by caleucheg** [lizixian18/MusicLibrary#154]
在StarrySkyConfig 中配置了关闭通知栏    builder.setOpenNotification(false); 但是一些设备上还会报错

**Comment by EspoirX** [comment]
给点日志

**Comment by caleucheg** [comment]
1 java.lang.RuntimeException:Unable  to stop service com.lzx.starrysky.MusicService@421ea15:  java.lang.NullPointerException: Attempt to invoke interface method 'void  com.lzx.starrysky.notification.INotification.stopNotification()' on a  null object reference
--
2 android.app.ActivityThread.handleStopService(ActivityThread.java:4038)
3 ......
4 java.lang.NullPointerException:Attempt  to invoke interface method 'void  com.lzx.starrysky.notification.INotification.stopNotification()' on a  null object reference
5 com.lzx.starrysky.MusicService.onDestroy(MusicService.java:119)
6 android.app.ActivityThread.handleStopService(ActivityThread.java:4018)
7 android.app.ActivityThread.access$1900(ActivityThread.java:229)
8 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1907)
9 android.os.Handler.dispatchMessage(Handler.java:106)
10 android.os.Looper.loop(Looper.java:226)
11 android.app.ActivityThread.main(ActivityThread.java:7212)
12 java.lang.reflect.Method.invoke(Native Method)
13 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:576)
14 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:956)

**Comment by EspoirX** [comment]
收到
