### ISSUE TITLE
倒序播放

### ISSUE THREAD

**Issue by meanhan** [lizixian18/MusicLibrary#157]
调整播放列表为倒序  正在播放的index没有变  请问有什么办法修改吗？

**Comment by EspoirX** [comment]
我先看下是不是有bug

**Comment by meanhan** [comment]
建议可以加一个倒序播放功能

**Comment by EspoirX** [comment]
好，目前在优化，有什么建议也可以提

**Comment by EspoirX** [comment]
倒序播放已添加

**Comment by meanhan** [comment]
请问 倒序播放功能 在哪个版本？implementation 'com.lzx:StarrySkyKt:x.x.x'  版本号是多少？

**Comment by EspoirX** [comment]
<img width="392" alt="WX20200430-115748@2x" src="https://user-images.githubusercontent.com/16240767/80670574-dc7df500-8ad9-11ea-9b0f-d31713934d47.png">
