### ISSUE TITLE
通知栏切歌不起作用

### ISSUE THREAD

**Issue by gaoyl87** [lizixian18/MusicLibrary#159]
v2.4.1版本
直接跑的demo
复现流程
1. 打开首页，点击播放任一首歌
2. 回退桌面
3. 在通知栏点上一首或下一首，切歌都无效
在首页未关闭状态下，通知栏切歌没问题

**Comment by EspoirX** [comment]
我试了下可以切，你要不用demo debug一下，看看哪里有问题？

**Comment by gaoyl87** [comment]
回退桌面 不是按home键回退，是按返回键把activity都退掉，麻烦再试试。我这边试了，在activity都退出的情况下，播放状态下按通知栏的暂停键，通知栏会关掉

**Comment by EspoirX** [comment]
原因是把 activity 都退掉后，在拦截器里面获取权限的框架中需要获取栈顶Activity，由于没有，所以内部报崩溃了，导致拦截器走不下去。
内部图片加载的上下文也是获取当前Activity的，不作处理同样也会有问题，所以在图片加载这里会更新一下，如果当前没有activity就用Application的上下文
demo 我完善了一下，应该没问题了
