### ISSUE TITLE
现在可否在实际项目使用?

### ISSUE THREAD

**Issue by Zhangxd77** [lizixian18/MusicLibrary#16]
准备在实际项目中使用，看到22个小时之前还有更新，是否现在功能完善？可以实际使用？

**Comment by lizixian18** [comment]
可以使用了，我收到反馈也有很多人正在使用中，现在基本稳定了，现在这个项目的状态就是在使用中如果发现有Bug，我这边收到反馈后，就会作对应的修复，最近一次更新是因为发现一些bug，你可以看看版本更新记录。

**Comment by lizixian18** [comment]
如果你在使用过程中，有出现问题或者需求，都可以反馈，我会尽量满足的。
![qq 20180426141557](https://user-images.githubusercontent.com/16240767/39288873-606250bc-495c-11e8-9a9d-d6e777690919.jpg)

**Comment by Zhangxd77** [comment]
太好了，谢谢，那我就集成进来了
