### ISSUE TITLE
倒序播放问题

### ISSUE THREAD

**Issue by meanhan** [lizixian18/MusicLibrary#160]
1、倒序播放列表循环模式，播放至最后一首（实际上为正序第一首时），没有列表循环继续播放；
2、倒序播放模式 ，下一首 上一首 切歌时，还是按照正序播放的顺序切歌；
3、列表循环模式，播放至第一首时，切上一首    是否也加上循环播放功能。

**Comment by EspoirX** [comment]
第一第三点我看看，第二点是正常的
