### ISSUE TITLE
锁屏通知栏切歌问题

### ISSUE THREAD

**Issue by meanhan** [lizixian18/MusicLibrary#162]
版本2.4.2  锁屏通知栏 切换上一首 下一首  只切换歌曲，封面图没有切换，也接收不到广播。 不锁屏时时没问题的

**Comment by meanhan** [comment]
已解决  将自定义GlideImageLoader中context 修改为application context解决

**Comment by EspoirX** [comment]
默认取的是当前activity的上下文，可能锁屏的时候获取不到导致的，这个已经解决，但是还没打包
