### ISSUE TITLE
请问多个音频分别单独播放 单独控制 现在有这功能么

### ISSUE THREAD

**Issue by xuexirong** [lizixian18/MusicLibrary#164]

**Comment by EspoirX** [comment]
设置模式设成单曲播放就行

**Comment by xuexirong** [comment]
好的，谢谢，我试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Espoir <notifications@github.com&gt;
发送时间: 2020年5月27日 12:50
收件人: EspoirX/StarrySky <StarrySky@noreply.github.com&gt;
抄送: xuexirong <779285112@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[EspoirX/StarrySky] 请问多个音频分别单独播放 单独控制 现在有这功能么 (#164)
