### ISSUE TITLE
Playlist stops playing when run in the background

### ISSUE THREAD

**Issue by dovahkrid** [lizixian18/MusicLibrary#166]
The whole `MediaSessionConnection` seems doesn't work when the app plays in the background after a few songs. The `nowPlaying` won't update, so `mediaHasChanged` in `ExoPlayback` will be false and the music stop.

`MediaSessionConnection` will "revive" when the app is opened again, but it's already late.

**Comment by dovahkrid** [comment]
1 more issue: The players stop switching new song when the screen turned off after a few songs. It plays again when turn on the screen (unlock not required). This only happens on Android 9 Pie.

**Comment by EspoirX** [comment]
Please use the latest version
