### ISSUE TITLE
以module形式引入 播放音乐方法用不了，在线、本地都不能放 一用就闪退 

### ISSUE THREAD

**Issue by godgodfather** [lizixian18/MusicLibrary#167]
abstract method "int com.google.android.exoplayer2.audio.SimpleDecoderAudioRenderer.supportsFormatInternal(com.google.android.exoplayer2.drm.DrmSessionManager, com.google.android.exoplayer2.Format)"

异常信息如下

**Comment by Shark-Lucas** [comment]
我也遇到了这个问题 请问解决了吗

**Comment by EspoirX** [comment]
https://github.com/google/ExoPlayer/issues/3511    应该是这个问题，如果没你什么要求可以先用系统播放器用着先，demo有例子，改改就行，后面看升级一下播放器版本会不会好。

**Comment by EspoirX** [comment]
请用2.4.5版本，有问题欢迎进行反馈
