### ISSUE TITLE
进度条问题

### ISSUE THREAD

**Issue by booldplx** [lizixian18/MusicLibrary#174]
大佬，我有一个列表页面播放音乐，第一次进入播放列表的音乐都正常，进度条回调ok，但当我退出页面的时候调用StarrySky.with().clearPlayerEventListener();和StarrySky.with().stopMusic(); 再次进入页面播放的时候，第一次点击播放的时候，进度条没有反应了，TimerTaskManager没有回调，然后我再次点击别的item播放，TimerTaskManager又有回调了，求帮忙 谢谢

**Comment by booldplx** [comment]
第二次进入页面点击播放的时候，先回调了onPlayerStop，请问这是什么情况呢

**Comment by EspoirX** [comment]
贴一下你的代码

**Comment by EspoirX** [comment]
请用2.4.5版本，有问题欢迎进行反馈
