### ISSUE TITLE
StarrySky.with().playMusicById(songId) first player onPlayerStart not invoked

### ISSUE THREAD

**Issue by asugar** [lizixian18/MusicLibrary#178]
this problem happened only app first star up，after everything is ok。anybody has this problem？

MediaControllerCompat playFromMediaId cannot callback for first start up app

**Comment by asugar** [comment]
the reason：MediaControllerCallback --> onPlaybackStateChanged :val songId = getNowPlaying()?.id songId = ""

**Comment by EspoirX** [comment]
It has been fixed, please use version 2.4.5
