### ISSUE TITLE
MediaButtonReceiver component may not be null.

### ISSUE THREAD

**Issue by asugar** [lizixian18/MusicLibrary#186]
Fatal Exception: java.lang.RuntimeException
Unable to create service com.lzx.starrysky.MusicService: java.lang.IllegalArgumentException: MediaButtonReceiver component may not be null.

目前只有android4.4.4版本有此问题，

问题原因是：MediaButtonReceiver下的getMediaButtonReceiverComponent返回了null

1）在manifest中有MediaButtonReceiver的注册：
```
<receiver android:name="android.support.v4.media.session.MediaButtonReceiver">
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_BUTTON" />
            </intent-filter>
        </receiver>
```
2）目前工程升级了androidx

**Comment by asugar** [comment]
<receiver android:name="androidx.media.session.MediaButtonReceiver" >
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_BUTTON" />
            </intent-filter>
        </receiver>

**Comment by asugar** [comment]
```
<receiver android:name="androidx.media.session.MediaButtonReceiver" >
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_BUTTON" />
            </intent-filter>
        </receiver>
```

**Comment by EspoirX** [comment]
已fix
