### ISSUE TITLE
锁屏页下歌曲名显示问题

### ISSUE THREAD

**Issue by shenbengit** [lizixian18/MusicLibrary#19]
![s80510-205458](https://user-images.githubusercontent.com/24364422/39870720-ed0019d0-5494-11e8-977d-14c1b8123d73.jpg) 正常情况下不是该显示正在播放的歌曲名吗？为啥我这显示的是app的名称？

**Comment by lizixian18** [comment]
刚用魅族手机做了测试，结果是一定要设置封面才能正常显示，至于显示app的名称这个，是系统行为，比如魅族就显示 MEIZU Music 字样，所以你可以设置个封面看看结果怎么样，因为缺手机，其他手机还没测试。

**Comment by shenbengit** [comment]
ok，一会我测试一下。

**Comment by shenbengit** [comment]
![image](https://user-images.githubusercontent.com/24364422/39905288-212dc4bc-550f-11e8-8660-9f36e020ad08.png)
现在设置了，还是没有效果。按钮点击事件均可用。

**Comment by lizixian18** [comment]
你是什么手机

**Comment by shenbengit** [comment]
魅族，O(∩_∩)O，要不你告诉我在那里实现锁屏功能，还没找到，尴尬。

**Comment by lizixian18** [comment]
QueueHelper#fetchInfoWithMediaMetadata方法，数据赋值在这里面

**Comment by shenbengit** [comment]
问题已经解决了，就是要设置封面才能正确显示音乐名，刚刚没效果是因为我设置setSongCover()没有设置成功。谢谢。

**Comment by lizixian18** [comment]
路径错了吗

**Comment by shenbengit** [comment]
嗯，
![image](https://user-images.githubusercontent.com/24364422/39910276-2148469c-5529-11e8-97ee-0cbbcc38501d.png)这里如果音乐名过长，可以改成跑马灯形式吗？

**Comment by lizixian18** [comment]
这个是系统的播放器，得看具体系统它自己的操作了，可能跑马灯，可能省略号也不一定，，你可以写死一个看看效果

**Comment by shenbengit** [comment]
好的，我试试。

**Comment by shenbengit** [comment]
![image](https://user-images.githubusercontent.com/24364422/39918077-00d3c4e0-5542-11e8-8f9a-8d0c8ea65318.png) 有什么方法可以监听点击了上一首、下一首按钮点击事件吗？

**Comment by lizixian18** [comment]
我暂时还没写监听这两个按钮的方法
