### ISSUE TITLE
无法播放raw文件啊

### ISSUE THREAD

**Issue by duxxz** [lizixian18/MusicLibrary#193]
暴露个api支持下呗，大佬， exo都支持的

**Comment by EspoirX** [comment]
可以播放的，你看下是不是路径没传对吧

**Comment by duxxz** [comment]
> 可以播放的，你看下是不是路径没传对吧

不行的 因为raw是打包进apk的. 它的路径 转 url 是: android.resource://package_name/ 会提示非法的文件路径

exo里边的播放是转Uri转MediaSource进行播放, 你可以试试

**Comment by EspoirX** [comment]
要不你放在assets里？

**Comment by duxxz** [comment]
> > 可以播放的，你看下是不是路径没传对吧
> 
> 不行的 因为raw是打包进apk的. 它的路径 转 url 是: android.resource://package_name/ 会提示非法的文件路径



> 要不你放在assets里？

assets是一样的咯. 只是一个编译 跟 不编译的区别, 除非copy文件出来缓存目录
