### ISSUE TITLE
当前播放器，是不是不支持aac、m4a格式的音频，我这边播放没有声音。如果没有支持是不是需要自己重新编译so库

### ISSUE THREAD

**Issue by zhu528** [lizixian18/MusicLibrary#197]

**Comment by EspoirX** [comment]
支持

**Comment by zhu528** [comment]
但是我这边播放的时候，没有声音。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "EspoirX/StarrySky"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月2日(星期一) 下午3:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [EspoirX/StarrySky] 当前播放器，是不是不支持aac、m4a格式的音频，我这边播放没有声音。如果没有支持是不是需要自己重新编译so库 (#197)





 
支持

**Comment by zhu528** [comment]
现在我项目使用的版本是 2.4.4 版本
