### ISSUE TITLE
什么时候能适配下Android10以上、API30以上？目前设置了缓存不生效

### ISSUE THREAD

**Issue by weiqt** [lizixian18/MusicLibrary#199]
什么时候能适配下Android10以上、API30以上？目前设置了缓存不生效

**Comment by EspoirX** [comment]
10以下有问题吗

**Comment by weiqt** [comment]
没有10以下的手机，我现在手机是Android10，API设置了29，并不能创建000StarrySkyCache这个文件夹
        StarrySky.init(this)
            .setOpenCache(true)
            .setAutoManagerFocus(false)   //使用多实例的时候要关掉，不然会相互抢焦点
            .setCacheDestFileDir("000StarrySkyCache/".toSdcardPath())
//            .setCacheDestFileDir(PathUtils.getExternalAppCachePath())
            .setCacheMaxBytes(1024 * 1024 * 1024)  //设置缓存上限，默认 512 * 1024 * 1024
            //.setCache(AndroidVideoCache(this))
//            .addInterceptor(PermissionInterceptor(this))
            .setNotificationSwitch(true)
//            .setNotificationType(INotification.CUSTOM_NOTIFICATION)
            .apply()

**Comment by weiqt** [comment]
建议您把sdk version设置到29、30试一下

**Comment by EspoirX** [comment]
缓存路径用沙盒就好
