### ISSUE TITLE
通知栏被清除

### ISSUE THREAD

**Issue by Silnt** [lizixian18/MusicLibrary#20]
是否有方法控制 通知栏能否被清除 
例如 音频播放时 不可被清除  没有播放时 可以被清除 Service.stopForeground(true)？

**Comment by lizixian18** [comment]
你在播放的时候也能被清除吗？  代码清除通知栏调用 MusicManager.get().stopNotification(); 看看

**Comment by Silnt** [comment]
`
![1526011347 1](https://user-images.githubusercontent.com/21040178/39907222-d3329494-5519-11e8-9e73-99b9be761439.jpg)
![1526014185 1](https://user-images.githubusercontent.com/21040178/39907223-d385ed2e-5519-11e8-81d3-5418ecdd7eec.jpg)

`

**Comment by lizixian18** [comment]
这个按钮，好的，我看看，晚点回复你

**Comment by Silnt** [comment]
好的

**Comment by lizixian18** [comment]
我找不到这样的手机，你可以配合我测试一下吗

**Comment by Silnt** [comment]
可以

**Comment by lizixian18** [comment]
你qq多少

**Comment by Silnt** [comment]
511619019

**Comment by lizixian18** [comment]
该功能将会在1.3.3实现

**Comment by danhanxiang** [comment]
demo  音乐播放不了 通知栏也显示不了， 然后我配置通知栏 显示不了，

**Comment by lizixian18** [comment]
有没有报什么错之类的，看看

**Comment by danhanxiang** [comment]
![default](https://user-images.githubusercontent.com/19224837/44084594-b4c344fc-9fe9-11e8-9c30-319cecf7f344.png)

你的demo 跑起来了但是播放什么都不行，根据你的通知栏配置，但是我不现实，

**Comment by lizixian18** [comment]
额……你加我qq吧

**Comment by danhanxiang** [comment]
你扣扣多少

**Comment by lizixian18** [comment]
386707112
