### ISSUE TITLE
在fragment中如何移除进度监听？

### ISSUE THREAD

**Issue by NCheng8835** [lizixian18/MusicLibrary#202]
在单Activity的app中，fragment中添加了监听，但是没有相应的移除方法，导致内存泄漏，想问下后续会适配下吗？

**Comment by EspoirX** [comment]
Activity destroy 时会自动移除，目前还没考虑到单Activity，你可以不用封装好的api去监听进度，直接用TimerTaskManager这个类去实现监听。
