### ISSUE TITLE
隐私合规问题：获取运行中进程信息

### ISSUE THREAD

**Issue by bingdu0** [lizixian18/MusicLibrary#209]
版本号：2.6.5
应用宝检测：获取运行中进程信息

**Comment by EspoirX** [comment]
放同意之后再初始化

**Comment by jarvan11** [comment]
> 放同意之后再初始化

@EspoirX 大佬，不是说一定要在Application中完成么？我放在启动页或者MainActivity初始化确实不行

![Image](https://github.com/user-attachments/assets/658533ab-d258-4d59-9cdc-de973b9f7564)
