### ISSUE TITLE
你好，我在使用框架时候遇到个问题，麻烦您看到给与回复，谢谢，很急

### ISSUE THREAD

**Issue by Zhangxd77** [lizixian18/MusicLibrary#21]
我使用onPlayCompletion（）当前音频播放完毕的时候，想让他播放下一个，代码部分是这么写的。但是他却还是播第一个，您知道什么问题吗，谢谢
`
     if (MusicManager.get().hasNext()) {
                    MusicManager.get().playNext();
                }
`
![image](https://user-images.githubusercontent.com/20806535/40108607-fc3f1eee-592d-11e8-82d8-2678d8513ca8.png)

**Comment by Zhangxd77** [comment]
截图是onMusicSwitch（）打印这个里面，打印出来的，本来应该是播放002，但是一下子打印出来两个url

**Comment by Zhangxd77** [comment]
我好像说的有点混乱。。请您看这一条。我放了个列表，第一个播放完之后，应该播放第二语音，if (MusicManager.get().hasNext()) { MusicManager.get().playNext(); }
代码是这么写的。但是这么写之后，从头播放了第一个，并没有播放第二个，麻烦您了！！

**Comment by Zhangxd77** [comment]
然后我自己有代码逻辑写，播放哪一个，也控制不了，他只能播放第一个，但是我打印url position都是对的

**Comment by lizixian18** [comment]
用得哪个版本

**Comment by lizixian18** [comment]
很急的话可以加我qq386707112我比较容易看到

**Comment by lizixian18** [comment]
原因：API使用不正确，已解决
