### ISSUE TITLE
希望添加一个注意事项

### ISSUE THREAD

**Issue by Fanketly** [lizixian18/MusicLibrary#214]
我在使用过程中，不时会发生点击无法播放的情况。经过排查，最后发现是因为service在没连接成功的情况下，监听了播放状态，导致了无法播放。所以我添加了一个全局的livedata用来通知service的连接情况。

**Comment by EspoirX** [comment]
初始化的时候可以监听service连接成功

**Comment by Fanketly** [comment]
我也是用了这个方法，但是我想表达的是添加这个注意事项，免得更多人踩坑
