### ISSUE TITLE
State.STATE_IDLE这个播放状态没有

### ISSUE THREAD

**Issue by zhengjiong** [lizixian18/MusicLibrary#22]
得到播放状态 ，返回值为State中的下列之一: 
State.STATE_IDLE 空闲
State这个枚举根本就没有啊, 而且support-media-compat中也没有这个STATE_IDLE(我用的27.1.1版本), STATE_PAUSED倒是有.

**Comment by lizixian18** [comment]
如果没还没播放过 state=State.STATE_NONE，播放过 state=State.STATE_IDLE

**Comment by lizixian18** [comment]
感觉状态有点多，后面会去掉 State.STATE_NONE

**Comment by zhengjiong** [comment]
对的 是找不到这个类 我现在用的是support-media-compat中的State, 但是他没有idle

**Comment by lizixian18** [comment]
有啊，你看我都能找到了
![qq 20180521143116](https://user-images.githubusercontent.com/16240767/40293471-ad78c6dc-5d03-11e8-8786-fcfc8cb315d8.png)

**Comment by zhengjiong** [comment]
找到了 不好意思

**Comment by zhengjiong** [comment]
这android studio出问题, 快捷键居然找不到

**Comment by lizixian18** [comment]
重启一下就行
