### ISSUE TITLE
请问能支持rtmp吗?

### ISSUE THREAD

**Issue by zhengjiong** [lizixian18/MusicLibrary#23]
我看是能支持m3u8的, 但是不支持rtmp,比如说这个
rtmp://live.hkstv.hk.lxdns.com/live/hks

**Comment by lizixian18** [comment]
我试一下看看

**Comment by lizixian18** [comment]
用的是ExoPlayer，ExoPlayer如果不支持的话，就不支持了……

**Comment by zhengjiong** [comment]
我查了一下ExoPlayer支持这个

**Comment by zhengjiong** [comment]
好像要引入com.google.android.exoplayer:extension-rtmp

**Comment by lizixian18** [comment]
嗯，我今天查查相关资料，如果可以的话我就看看如何加入进去

**Comment by lizixian18** [comment]
是用你上面给的地址做测试就可以了是吧

**Comment by zhengjiong** [comment]
恩 可以的 :smile:

**Comment by lizixian18** [comment]
好的，有消息就回复你

**Comment by lizixian18** [comment]
已完成对 rtmp 的支持了
