### ISSUE TITLE
通知栏创建时间显示问题

### ISSUE THREAD

**Issue by yhsj0919** [lizixian18/MusicLibrary#24]
通知栏默认有一个创建时间，不应该显示，在安卓8（miui10）上，折叠后，直接挤压歌名部分（刚开始我以为是歌曲播放时间，尴尬）

**Comment by lizixian18** [comment]
好的，我加个开关来设置这个时间是否需要显示吧

**Comment by yhsj0919** [comment]
如果需要音乐接口测试，明天找个时间发你一下7个主流音乐网站的搜索解析接口（仅作技术交流），根据网上的接口用kotlin实现的版本
