### ISSUE TITLE
请问播放异常态 调用端要怎么获知？

### ISSUE THREAD

**Issue by highBigger** [lizixian18/MusicLibrary#26]
com.pop.music:musicLibrary E/ExoPlayerImplInternal: Source error.
比如这种播放地址失效了，我这边要怎么才能获取到到发生了这种错误

**Comment by lizixian18** [comment]
获取具体错误信息？

**Comment by highBigger** [comment]
怎么感知到错误？

**Comment by lizixian18** [comment]
有回调 onError

**Comment by highBigger** [comment]
目前感觉是全被捕获了还是怎么了，就是播放错误，我这边没办法处理

**Comment by highBigger** [comment]
好的，我看看

**Comment by highBigger** [comment]
onError 可以考虑把异常抛过来么？

**Comment by lizixian18** [comment]
如果是异常，有捕获，如果是播放错误，会有回调
![qq 20180606160720](https://user-images.githubusercontent.com/16240767/41025132-b6caa848-69a3-11e8-8868-9f02e56bd702.png)

**Comment by lizixian18** [comment]
异常一般都是跟逻辑无关的，抛出来不太好吧

**Comment by highBigger** [comment]
到MusicManager 这层就只能监听到	
@Override
	public void onError(String errorMsg) {
		Log.e(TAG, "errorMsg");
	}
且每次errrorMsg都是空

**Comment by highBigger** [comment]
我的意思是我们有时候可能要根据异常类型做不一样的处理, 有些是无能为力的，有些是可以补救的，比如播放地址失效了，我可以重新获取最新的播放地址重播

**Comment by lizixian18** [comment]
刚看了下代码，具体错误信息这里被我屏蔽了，我也忘记为什么了=_=，我等下加回去，你说的这个错误类型的也有些道理，不过我要看看那些地方可以这样做才行

**Comment by highBigger** [comment]
setOpenCacheWhenPlaying 还有个问题，这个字段是控制什么？

**Comment by lizixian18** [comment]
边播边存的开关

**Comment by highBigger** [comment]
为false的话是播放不缓存？

**Comment by highBigger** [comment]
同一首歌单曲循环也一直走http?

**Comment by lizixian18** [comment]
默认是false，不缓存的话会读网络数据

**Comment by lizixian18** [comment]
不过单曲循环着我没具体细测，可以抓包看看

**Comment by highBigger** [comment]
所以我要把播放过的歌曲缓存下来，同一首歌重复播放走缓存是要打开这个开关？

**Comment by lizixian18** [comment]
嗯，初始化的时候可以配置缓存，播过的会缓存到本地

**Comment by lizixian18** [comment]
看看你代码

**Comment by highBigger** [comment]
06-06 16:26:52.500 7135-7310/com.pop.music:musicLibrary E/ExoPlayerImplInternal: Source error.
    com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://127.0.0.1:34542/http%3A%2F%2Fm10.music.126.net%2F20180606164649%2F76ab7b07289ef814f51989747915b2a7%2Fymusic%2Fc89e%2F9537%2Ff242%2Ffc5ba8518d5a25455058f9777c97d26a.mp3

**Comment by highBigger** [comment]
MusicLibrary musicLibrary = new MusicLibrary.Builder(this)
            .setCacheConfig(DEFAULT)
            .build();
        musicLibrary.init();

**Comment by highBigger** [comment]
这个感觉代理出问题了url 拼接出问题了http://127.0.0.1:34542/http%3A%2F%2Fm10.music.126.net%2F20180606164649%2F76ab7b07289ef814f51989747915b2a7%2Fymusic%2Fc89e%2F9537%2Ff242%2Ffc5ba8518d5a25455058f9777c97d26a.mp3

**Comment by lizixian18** [comment]
缓存地址改成   CacheUtils.getStorageDirectoryPath()+“/pop/music/song-cache/”

**Comment by lizixian18** [comment]
因为现在抛异常的地方主要有 IPC通信的时候的RemoteException，网络访问的 IOException ，感觉不需要回调onError啊

**Comment by highBigger** [comment]
我觉得，还是有些必要的，最好给调用者更多的处理空间。

**Comment by highBigger** [comment]
还有个问题是列表循环播放的时候如列表只有一首曲，是不会循环。

**Comment by highBigger** [comment]
还有个问题请教下：
	比如	这样调用	第奇数次
        mMusicManager.playMusic(List<SongInfo> list, 0);
        是会播放（resume）歌曲，为啥第偶数次同样这样调用是暂停，没摸懂

**Comment by lizixian18** [comment]
列表循环这个，我知道了，第二个问题，是因为里面自动判断了播放暂停，如果你想每次都重新播，那你传多一个参数true，这我api文档有写

**Comment by highBigger** [comment]
👌

**Comment by highBigger** [comment]
还有个需求，不知道好不好支持，想要分两个cache, 自己收藏的列表的歌曲缓存不清理，其他的歌曲就随意

**Comment by lizixian18** [comment]
可以实现，我跟你两下思路，其实缓存就是存在你手机文件夹里面的文件，而文件的命名是音频url的md5，所以你可以根据这个去匹配你想删或不想删的文件就行，如果我提供的方法不满足你，其实你这个功能完全可以自己实现，因为说到底就是一个操作文件的功能罢了
