### ISSUE TITLE
8.0异常，8.0以上版本中不允许创建后台服务，Notification都需要依附一个channel

### ISSUE THREAD

**Issue by 1378282082** [lizixian18/MusicLibrary#27]
![_20180607095140](https://user-images.githubusercontent.com/19813879/41074133-138cafb6-69f6-11e8-9f88-fef9eb7505f1.png)
在8.0及以上版本中出现此错误，大概原因就是8.0以上版本中不允许创建后台服务，Notification都需要依附一个channel，望尽快修复

**Comment by lizixian18** [comment]
错误信息可以截全一点吗

**Comment by 1378282082** [comment]
![1528343880 1](https://user-images.githubusercontent.com/19813879/41077849-99950128-6a08-11e8-97cd-8024b6e954b4.jpg)
MusicManager.init()中没有找到判断8.0以上的代码，是直接启动服务的

**Comment by 1378282082** [comment]
![_20180607120056](https://user-images.githubusercontent.com/19813879/41077921-2506f856-6a09-11e8-985f-6bb3b7cf5979.png)

**Comment by lizixian18** [comment]
添加了以下更改
```
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                mContext.startForegroundService(intent);
          }else {
              mContext.startService(intent);
          }
     }
```
