### ISSUE TITLE
【功能建议】播放模式增加倒序播放

### ISSUE THREAD

**Issue by imliujun** [lizixian18/MusicLibrary#29]
目前很多FM、知识付费类型的音频内容都是连载形式的，播放的时候希望能够支持倒序播放，是否考虑增加支持？

**Comment by lizixian18** [comment]
倒序是什么意思，是从最后一首往前播吗

**Comment by imliujun** [comment]
倒序就是从当前播放的歌曲往上播，现在的顺序播放是从当前歌曲往下播

**Comment by lizixian18** [comment]
OK，明白，可以支持，下个版本上吧，刚好遇到一些bug要改。

**Comment by lizixian18** [comment]
当倒序到第一首的时候，播完是暂停还是到最后一首？

**Comment by imliujun** [comment]
直接就播完了吧，其实和顺序播放是一样的逻辑，只是一个向下一个向上

**Comment by lizixian18** [comment]
将在新版中添加
