### ISSUE TITLE
能不能只播放一个url 其他什么都不传？

### ISSUE THREAD

**Issue by zhangshaobo87** [lizixian18/MusicLibrary#3]

**Comment by lizixian18** [comment]
如果你没使用通知栏的话，转一个url，传一个id ，即 setSongId 和 setSongUrl ，如果你只有一个url，那id和url一样就行，试试看有没有问题。

**Comment by zhangshaobo87** [comment]
好的 我试试

**Comment by lizixian18** [comment]
大兄弟，看来还要传多几个参数，可以看看这个issues  [音乐播放不了](https://github.com/lizixian18/MusicLibrary/issues/4)
