### ISSUE TITLE
获取当前播放对象和进度异常

### ISSUE THREAD

**Issue by imliujun** [lizixian18/MusicLibrary#30]
点击播放，然后有几率抛出这个异常，我开启了100毫秒一次读取播放进度

![image](https://user-images.githubusercontent.com/9779970/41391157-827114dc-6fcb-11e8-8e78-e02c2bcf57b7.png)
![image](https://user-images.githubusercontent.com/9779970/41391194-c0171e94-6fcb-11e8-8555-8b3acbb9027c.png)

**Comment by lizixian18** [comment]
好，我测试一下，最好1秒一次吧

**Comment by imliujun** [comment]
因为我这边的音波效果需要100毫秒更新一次，所以需要频繁访问 getCurrPlayingMusic  getProgress，这一块的性能和线程安全问题不知道怎么样？

**Comment by lizixian18** [comment]
我测试完给你回复

**Comment by lizixian18** [comment]
我测试了一下，100毫秒获取一次应该没什么问题，我想你应该是8.0系统吧，应该是 8.0 以上 startForegroundService 启动服务如果一定时间内不调用 startForeground 的话就会报 ANR，然后进程就死了导致的。如果是这样的话，在新版应该就修复了。

**Comment by imliujun** [comment]
没错，我是8.0系统，我更新看还会不会出现这个问题
