### ISSUE TITLE
与腾讯云播放集成有冲突

### ISSUE THREAD

**Issue by fandazeng** [lizixian18/MusicLibrary#31]
Process: com.wmzx.unicorn:musicLibrary, PID: 26050
    java.lang.UnsatisfiedLinkError: No implementation found for void com.tencent.liteav.basic.log.TXCLog.nativeLogInit() (tried Java_com_tencent_liteav_basic_log_TXCLog_nativeLogInit and Java_com_tencent_liteav_basic_log_TXCLog_nativeLogInit__)
        at com.tencent.liteav.basic.log.TXCLog.nativeLogInit(Native Method)
        at com.tencent.liteav.basic.log.TXCLog.init(TXCLog.java:31)
        at com.tencent.liteav.basic.log.TXCLog.setConsoleEnabled(TXCLog.java:52)

集成musicLibrary库之后，腾讯云播放的集成会报错，是musicLibrary在新进程造成的吗？求解（去掉musicLibrary库之后项目没任何问题）

**Comment by imliujun** [comment]
你的Application中的初始化代码没有做进程判断吧
新启动一个进程会运行Application的onCreate方法，判断调用onCreate方法的进程是不是主进程，如果不是主进程就return，防止初始化的代码执行两次

**Comment by fandazeng** [comment]
放在主进程里面初始化可以了

**Comment by lizixian18** [comment]
初始化的文档我修改一下吧，免得引起一些歧义，如果不想放在Application上初始化，可以放在你的MainActivity里面初始化，这样就不用判断进程了。
