### ISSUE TITLE
设置音乐播放列表，第一首歌默认是播放状态，但现在想实现的功能是进入列表不自动播放，所以全部显示成暂停的界面，这个如何解决？

### ISSUE THREAD

**Issue by JeremyHwc** [lizixian18/MusicLibrary#33]
数据初始化：
       MusicManager.get().setPlayList(mDatas);
        //添加一个观察者
        MusicManager.get().addStateObservable(mAdapter);

Adapter代码：
        boolean musicPlaying = MusicManager.isCurrMusicIsPlayingMusic(item);
            helper.setVisible(R.id.elib_iv_check, !musicPlaying);
            if (musicPlaying) {
                musicPlayWaveView.setVisibility(View.VISIBLE);
                musicPlayWaveView.start();
            } else {
                musicPlayWaveView.setVisibility(View.GONE);
                musicPlayWaveView.stop();
            }

但是我发现这样子调用代码，播放列表第一个的状态永远是在播放状态，我现在是想进入音乐列表时，全部是暂停的状态，显示暂停的UI，即使我在MusicManager.get().addStateObservable(mAdapter);后面添加上MusicManager.get().stopMusic();第一首歌还是处于播放状态

**Comment by lizixian18** [comment]
不是太明白，可否贴上UI，和你adapter的代码说说要实现的效果是怎么样的。可能这样会明白一点。

**Comment by imliujun** [comment]
同问，我的场景是：每次启动APP时，需要恢复播放器之前的数据和进度，我的代码如下：
```kotlin
playMusic(playList, index)
 pauseMusic()
 if (progress > 0) {
       seekTo(progress)
 }
```
但是这个代码无效，播放列表为空。不过我在debug断点这个代码的时候执行完playMusic方法就开始播放出声音了，然后继续往下执行就生效了。

**Comment by JeremyHwc** [comment]
[public class ELibDataAdapter extends BaseQuickAdapter<SongInfo, MultipleViewHolder> implements Observer {
    private final String DOC_TYPE_VIDEO = "mp4";
    private final String DOC_TYPE_AUDIO = "mp3";
    private final String DOC_TYPE_DOCMENT_PDF = "pdf";
    private final String DOC_TYPE_DOCMENT_WORD_DOC = "doc";
    private final String DOC_TYPE_DOCMENT_WORD_DOCX = "docx";


    public ELibDataAdapter(@LayoutRes int layoutResId, @Nullable List<SongInfo> data) {
        super(layoutResId, data);
    }

    @Override
    protected void convert(MultipleViewHolder helper, SongInfo item) {
        TempInfo tempInfo = item.getTempInfo();
        String docExt = item.getTempInfo().getTemp_1();
        helper.setImageResource(R.id.elib_iv_type, DOC_TYPE_VIDEO.equals(docExt) ? R.drawable.elib_video :
                (DOC_TYPE_AUDIO.equals(docExt) ? R.drawable.elib_audio_play :
                        (DOC_TYPE_DOCMENT_PDF.equals(docExt) ? R.drawable.elib_doc_pdf :
                                R.drawable.elib_doc_word)))
                .setText(R.id.elib_tv_type, item.getSongName())
                .setText(R.id.elib_tv_size, item.getSize())
                .setImageResource(R.id.elib_iv_check, (DOC_TYPE_VIDEO.equals(docExt) || DOC_TYPE_AUDIO.equals(docExt)) ? R.drawable.elib_video_play : R.drawable.elib_doc_play)
                .addOnClickListener(R.id.layout_item_elib_data_rl);
        //下面这一段是针对音频做的处理
        if (DOC_TYPE_AUDIO.equals(docExt)) {
            MusicPlayWaveView musicPlayWaveView = helper.getView(R.id.elib_wave_view);
            boolean musicPlaying = MusicManager.isCurrMusicIsPlayingMusic(item);
            helper.setVisible(R.id.elib_iv_check, !musicPlaying);
            if (musicPlaying) {
                musicPlayWaveView.setVisibility(View.VISIBLE);
                musicPlayWaveView.start();
            } else {
                musicPlayWaveView.setVisibility(View.GONE);
                musicPlayWaveView.stop();
            }
        }
    }

    @Override
    public void update(Observable o, Object arg) {
        //监听到状态改变，如果是开始和暂停两种的话就刷新adapter改变UI
        int msg = (int) arg;
        if (msg == MusicManager.MSG_PLAYER_START 
           || msg == MusicManager.MSG_PLAYER_PAUSE 
           || msg == MusicManager.MSG_MUSIC_CHANGE 
           || msg == MusicManager.MSG_PLAY_COMPLETION 
          || msg == MusicManager.MSG_PLAYER_STOP) {
            notifyDataSetChanged();
        }
    }
}]

我看这里无法贴图，上面针对音频部分做的处理是当前音乐在播放，显示一个波浪，表示正在播放，没有播放的音频显示暂停的按钮。

**Comment by lizixian18** [comment]
播放器实例是创建在第一次调用播放方法的时候，所以第一次调用播放包含了播放器创建和加载音乐的过程，而seekTo是播放器的方法，所以我猜测有可能在上面两个过程还没完成的时，就会无效，而当你调用playMusic(playList, index)的时候播放列表为空？

**Comment by lizixian18** [comment]
你是要实现一个列表里面哪个item在播放，那个item就显示播放动画这样的效果吗？类似这样的？
![qq 20180622110818](https://user-images.githubusercontent.com/16240767/41756014-a84a8b9c-760c-11e8-89b3-48eab93f0055.png)
@JeremyHwc

**Comment by imliujun** [comment]
@JeremyHwc  你需要调用setPlayListWithIndex方法来设置播放列表，这个方法不会自动播放

**Comment by imliujun** [comment]
@lizixian18 我的需求和他不一样的地方在于我调用setPlayListWithIndex方法后不能直接调用seekTo方法去设置进度，因为setPlayListWithIndex方法只是设置了数据，并没有让播放器去加载音频，所以seekTo无效。

但是我如果调用playMusic方法，又会自动开始播放，然后我们并不想自动播，只是想先加载音频到播放器，并且设置进度，让用户自己在播放列表点击播放按钮才继续播放

**Comment by JeremyHwc** [comment]
@lizixian18 
是的，就是那个item在播放，哪个item就显示动画。没播放的就没有动画，显示成暂停状态。就是第一次进来音乐列表的时候，第一个item通过MusicManager.isCurrMusicIsPlayingMusic(item);获取到的值是true，这个时候第一个item的动画就在进行，但是实际上音乐没有播放，没有声音。然后我点击其中的item，这个时候就能正常的显示对应item的动画。

**Comment by imliujun** [comment]
```kotlin
playMusic(playList, index)
 pauseMusic()
 if (progress > 0) {
       seekTo(progress)
  }
```
这段代码执行下来的结果是，播放器没有播出声音来，并且我调用 getPlayList去获取列表数据为空

**Comment by lizixian18** [comment]
你的效果是不是，打开界面，进度要显示上次播放的地方，但是这时候是不需要播放音乐的，当点击播放的时候才开始播？@imliujun

**Comment by imliujun** [comment]
@lizixian18 就是这个意思

**Comment by imliujun** [comment]
@JeremyHwc  isCurrMusicIsPlayingMusic 是判断当前的音乐是不是正在播放的音乐，并不代表这个音乐是播放状态，也可能是暂停状态。
isCurrMusicIsPlaying方法才是判断当前音乐是不是在播放

**Comment by lizixian18** [comment]
我觉得你做复杂了，这功能我在NiceMusic里面也有实现，你可以看看里面的代码，在 module/artist 包下 @JeremyHwc

**Comment by imliujun** [comment]
@JeremyHwc 这个方法我一开始也是理解错了，后面仔细看了会才搞明白

**Comment by lizixian18** [comment]
意思是你先调用setPlayList设置播放列表，然后再进入播放列表，那既然设置了，为什么还会空？还有你贴的代码，为什么调用播放后又马上调用暂停，这样没声音不很正常吗，我觉得我还是有点get不到你的意思，可以贴多点代码或者把操作流程完整说一下。@imliujun

**Comment by imliujun** [comment]
> 你的效果是不是，打开界面，进度要显示上次播放的地方，但是这时候是不需要播放音乐的，当点击播放的时候才开始播？

我需要实现这个效果，实现方式为播放器支持 ``setPlayListWithIndex(list , index , progress) ``  ，这样既设置了播放列表，调整了播放进度，又没有自动播放
