### ISSUE TITLE
updateRemoteViewUI方法可否加多一层判断

### ISSUE THREAD

**Issue by lzkc72** [lizixian18/MusicLibrary#34]
if (!TextUtils.isEmpty(mSongInfo.getAlbumInfo().getAlbumName())) {
            artistName = mSongInfo.getArtist() + " - " + mSongInfo.getAlbumInfo().getAlbumName();
        } else {
            artistName = mSongInfo.getArtist();
  }
因为app里面没有专辑的概念做通知栏的时候闪退了，后来去每一个设置播放列表的地方都去new了一个专辑信息

**Comment by lizixian18** [comment]
可以，谢谢提醒
