### ISSUE TITLE
获取音频时长问题？

### ISSUE THREAD

**Issue by JeremyHwc** [lizixian18/MusicLibrary#36]
我看到你的示例项目里面，音乐的时长是由后端返回的。
info.setDuration(object.getInt("file_duration") * 1000);   //音乐长度

现在我这边需要客户端通过url来获取音频的时长，MusicLibrary可以做到吗？

**Comment by JeremyHwc** [comment]
我通过getDuration()获取出来的时间都是0，是怎么回事呀

**Comment by lizixian18** [comment]
时机不对，在 onAsyncLoading 里面获取

**Comment by JeremyHwc** [comment]
这个方法里面获取依然是0额

**Comment by lizixian18** [comment]
看下代码？

**Comment by lizixian18** [comment]
或者你可以这样看看
![qq 20180625144758](https://user-images.githubusercontent.com/16240767/41834416-cc280432-7886-11e8-8331-a25394730d3b.png)

**Comment by JeremyHwc** [comment]
@Override
    public void onAsyncLoading(boolean isFinishLoading) {
        JLogUtil.showLogCompletion("isFinishLoading:"+isFinishLoading+"---duration:" + mSongInfo.getDuration(),"MTAG");
        updateUI(mSongInfo);
    }

    private void updateUI(SongInfo music) {
        if (music == null) {
            return;
        }
        mMusicSeekbar.setMax((int) music.getDuration());
        JLogUtil.showLogCompletion("duration:" + music.getDuration(),"MTAG");
        mTvMusicTotalTime.setText(formatMusicTime(music.getDuration()));
    }

打印出来的日志：
isFinishLoading:true---duration:0
duration:0
isFinishLoading:true---duration:0
duration:0
 I/MTAG: isFinishLoading:false---duration:0
duration:0

**Comment by lizixian18** [comment]
。。。  MusicManager.get().getDuration()

**Comment by JeremyHwc** [comment]
我搞错了 谢谢大佬

**Comment by windfone** [comment]
@JeremyHwc  老哥，你这个 onAsyncLoading 是在activity fragment 中复写的吗，我怎么没找到这个方法呢

**Comment by EspoirX** [comment]
这是旧版本的方法，现在没了，你有什么问题吗？
