### ISSUE TITLE
有关于通知渠道问题？

### ISSUE THREAD

**Issue by JeremyHwc** [lizixian18/MusicLibrary#37]
在android 8.0以上系统，每条通知都要属于一个对应的渠道，但是我看到库里面的notification_channel的值为MUSIC_LIB_Channel_ID，这样在应用信息打开“通知”管理的的时候，看到一个渠道是MUSIC_LIB_Channel_ID的渠道，建议能够提供方法改变这个渠道值。

**Comment by lizixian18** [comment]
会导致什么问题吗

**Comment by JeremyHwc** [comment]
这样用户看不懂MUSIC_LIB_Channel_ID 这个通知渠道是干什么的，可能被用户关闭

**Comment by JeremyHwc** [comment]
https://github.com/lizixian18/MusicLibrary/blob/master/Notification_README.md，这个文件不在了吗

**Comment by lizixian18** [comment]
https://github.com/lizixian18/MusicLibrary/blob/master/readme/notification.md
