### ISSUE TITLE
Android 8.0服务Service报错ANR

### ISSUE THREAD

**Issue by 1378282082** [lizixian18/MusicLibrary#38]
ActivityManager: ANR in com.dachun.dazhihui:musicLibrary
                                                  PID: 1612
                                                  Reason: Context.startForegroundService() did not then call Service.startForeground()

查阅资料可能是如下问题：
[https://blog.csdn.net/lylddingHFFW/article/details/78219327?locationNum=6&fps=1](url)

详细信息：
                                                  Load: 0.0 / 0.0 / 0.0
                                                  CPU usage from 5782ms to 0ms ago (2018-06-30 12:03:53.060 to 2018-06-30 12:03:58.842):
                                                    79% 1201/system_server: 60% user + 19% kernel / faults: 96056 minor 339 major
                                                    30% 2329/com.huawei.systemmanager:service: 25% user + 4.9% kernel / faults: 69166 minor 313 major
                                                    17% 7563/com.google.android.gms: 13% user + 3.9% kernel / faults: 6685 minor 131 major
                                                    1% 30189/com.huawei.appmarket: 0.7% user + 0.2% kernel / faults: 8874 minor 62 major
                                                    7.8% 4136/com.android.systemui: 6.1% user + 1.7% kernel / faults: 4619 minor 34 major
                                                    7.5% 2248/com.huawei.powergenie: 3.4% user + 4.1% kernel / faults: 4362 minor 30 major
                                                    0.8% 29192/android.process.media: 0.6% user + 0.2% kernel / faults: 828 minor 2 major
                                                    6.7% 423/logd: 3.9% user + 2.7% kernel / faults: 11 minor
                                                    6.3% 30843/adbd: 1.5% user + 4.8% kernel / faults: 2648 minor
                                                    6.2% 248/mmc-cmdqd/0: 0% user + 6.2% kernel
                                                    4.4% 8439/com.huawei.android.launcher: 3.4% user + 1% kernel / faults: 10906 minor 21 major
                                                    0.5% 15422/com.huawei.systemmanager: 0.3% user + 0.1% kernel / faults: 5732 minor 28 major
                                                    3.6% 660/android.hardware.graphics.composer@2.1-service: 0.5% user + 3% kernel
                                                    3.4% 690/surfaceflinger: 1.7% user + 1.7% kernel / faults: 102 minor
                                                    3.2% 1321/logcat: 1.2% user + 2% kernel / faults: 8054 minor
                                                    3% 2268/com.android.phone: 1.8% user + 1.2% kernel / faults: 1467 minor 21 major
                                                    2.9% 12379/kworker/u16:5: 0% user + 2.9% kernel
                                                    2.5% 727/dubaid: 1.5% user + 1% kernel / faults: 3450 minor
                                                    2.4% 424/servicemanager: 0.8% user + 1.5% kernel
                                                    2.4% 26400/kworker/0:2H: 0% user + 2.4% kernel
                                                    0.3% 7459/com.google.android.gms.persistent: 0.2% user + 0.1% kernel / faults: 1072 minor 695 major
                                                    1.7% 1132/kworker/u16:6: 0% user + 1.7% kernel
                                                    0.1% 2405/kworker/u16:10: 0% user + 0.1% kernel
                                                    1.3% 94/smcthread/0: 0% user + 1.3% kernel
                                                    1.3% 726/hwpged: 0.1% user + 1.2% kernel / faults: 7 minor
                                                    1.2% 23897/com.huawei.skytone: 1.2% user + 0% kernel / faults: 567 minor 6 major
                                                    0.1% 31502/kworker/u16:19: 0% user + 0.1% kernel
                                                    1% 31526/kworker/u16:21: 0% user + 1% kernel
                                                    0.8% 125/kswapd0: 0% user + 0.8% kernel
                                                    0.8% 262/ts_thread:0: 0% user + 0.8% kernel
                                                    0.8% 2221/com.huawei.hiview: 0.5% user + 0.3% kernel / faults: 161 minor 2 major
                                                    0.1% 2237/com.huawei.systemserver: 0% user + 0% kernel / faults: 301 minor 14 major
                                                    0.8% 3290/rild: 0.3% user + 0.5% kernel / faults: 37 minor 3 major
                                                    0.1% 8321/com.android.nfc: 0% user + 0% kernel / faults: 1667 minor 12 major
                                                    0.8% 10673/com.huawei.health:DaemonService: 0.8% user + 0% kernel / faults: 565 minor 5 major
                                                    0.8% 24214/com.alibaba.android.rimet: 0.6% user + 0.1% kernel / faults: 284 minor 179 major
                                                    0.8% 31448/kworker/u16:18: 0% user + 0.8% kernel
                                                    0% 27/kworker/4:0H: 0% user + 0% kernel
                                                    0.6% 504/netd: 0.1% user + 0.5% kernel / faults: 203 minor
                                                    0.6% 684/vendor.huawei.hardware.sensors@1.0-service: 0.3% user + 0.3% kernel / faults: 5 minor
                                                    0.6% 689/lmkd: 0% user + 0.6% kernel
                                                    0.6% 7595/com.baidu.input_huawei: 0.3% user + 0.3% kernel / faults: 681 minor 30 major
                                                    0% 7617/com.huawei.recsys: 0% user + 0% kernel / faults: 365 minor 8 major
                                                    0% 26820/com.huawei.intelligent: 0% user + 0% kernel / faults: 1039 minor 294 major
                                                    0.6% 32559/com.tencent.mm: 0.6% user + 0% kernel / faults: 299 minor 31 major
                                                    0.5% 1//init: 0.3% user + 0.1% kernel
                                                    0% 310/kworker/7:1H: 0% user + 0% kernel
                                                    0% 506/zygote: 0% user + 0% kernel / faults: 391 minor
                                                    0.5% 659/android.hardware.graphics.allocator@2.0-service: 0% user + 0.5% kernel / faults: 16 minor
                                                    0.5% 692/powerlogd: 0.5% user + 0% kernel / faults: 3 minor
                                                    0% 842/kworker/u16:1: 0% user + 0% kernel
                                                    0.5% 23840/kworker/u16:14: 0% user + 0.5% kernel
                                                    0% 32238/com.tencent.mm:exdevice: 0% user + 0% kernel / faults: 1218 minor 897 major
                                                    0.3% 3/ksoftirqd/0: 0% user + 0.3% kernel
                                                    0.3% 7/rcu_preempt: 0% user + 0.3% kernel
                                                    0% 31/kworker/5:0H: 0% user + 0% kerne

**Comment by 1378282082** [comment]
我看了下我用的是1.3.7，更新到1.3.8后，没有这个报错了，华为P10

**Comment by lizixian18** [comment]
是的，1.3.8才修复这个，没问题就好
