### ISSUE TITLE
音乐播放器的功能，你是怎么写出来的。

### ISSUE THREAD

**Issue by zhongwen1** [lizixian18/MusicLibrary#40]
我想问你试自己跟着google的api，一步步自己写出来的吗？想知道如何从无到有，到整个音乐播放器贡呢的完成。

**Comment by lizixian18** [comment]
开始之前先阅读大量的优秀开源项目源码，然后想好大概结构流程怎么样，参考别人写得好的地方，然后自己写出一个初步的版本，然后再慢慢的修改和迭代

**Comment by lizixian18** [comment]
参考别人项目主要是看如何使用一些设计模式，api如何设计等等，然后根据自己的理解写的。在写之前当然要对所涉及到的知识点都非常熟悉，写出初步版本之后就继续完善，然后根据其他人提出的问题或者建议一步一步完善。

**Comment by zhongwen1** [comment]
对所涉及到的知识点都非常熟悉 ，你是如何做对所需要的知识点了解，熟悉的呢？

**Comment by lizixian18** [comment]
这些靠你平时积累吧，或者你可以看文章看书什么的

**Comment by zhongwen1** [comment]
嗯，我觉得博客，文章，还有google 官网查看api，都可以。

**Comment by zhongwen1** [comment]
谢谢，楼主。

**Comment by lizixian18** [comment]
欢迎交流
