### ISSUE TITLE
Android 8.0初始化完成后，退出应用，通知栏显示后台耗电

### ISSUE THREAD

**Issue by 1378282082** [lizixian18/MusicLibrary#41]
在application中初始化musicLibrary后，进入应用未播放音频，然后退出应用，通知栏显示应用在后台消耗电量，手动杀掉应用，通知栏消失。如果进入应用播放过音频，再退出应用则不显示通知。不初始化musicLibrary，一切正常。 是因为初始化后启动Service了吗？

**Comment by lizixian18** [comment]
初始化就是启动服务，不过可以不一定要在 application 中初始化，你可以在需要的时候才初始化。

**Comment by 1378282082** [comment]
@lizixian18  我考虑过这个情况，在主页面初始化结果和上面的相同，如果在开始播放音频前初始化，可以避免这个情况，但是播放前再初始化耗时太久

**Comment by lizixian18** [comment]
那看你们产品接不接受了

**Comment by 1378282082** [comment]
有没有其他可以优化的方法

**Comment by lizixian18** [comment]
暂时想不到

**Comment by 1378282082** [comment]
好的，谢谢
