### ISSUE TITLE
快速切换歌曲导致列表选中歌曲与所播放的歌曲不一致

### ISSUE THREAD

**Issue by lzkc72** [lizixian18/MusicLibrary#42]
在列表中快速点击歌曲进行切换，会导致当前播放歌曲与所选中歌曲不一样！用你的NICEMUSIC试了一下，也是一样的问题

**Comment by lizixian18** [comment]
好，我会跟进这个问题。

**Comment by lzkc72** [comment]
加油，正在等待你的新版本

**Comment by lizixian18** [comment]
最近比较忙，可能没那么快，急的话你可以自己先做个处理，不让用户点这么快

**Comment by lzkc72** [comment]
好！

**Comment by lizixian18** [comment]
新版本已解决

**Comment by lzkc72** [comment]
项目下下来试了一下还是不行，速度也不用很快，在列表任意切换几首就会出现这个问题

**Comment by lizixian18** [comment]
还没打包上传呢，打包的不支持java10，我现在在降级，等多一会吧

**Comment by lzkc72** [comment]
哦哦，好，辛苦了！

**Comment by lizixian18** [comment]
主要修改就是在缓冲的时候，点击播放不会立马缓冲下一首，我自己试过，应该是没问题的

**Comment by lizixian18** [comment]
可以了，试试看。

**Comment by lzkc72** [comment]
不行，按你的说法应该不是我的问题，正常来说：最后播放的歌曲就是用户点击的最后一首歌(即列表所选中的与当前播放的是一致的)，应该是在缓冲的时候点击下一首就取消上一个任务立刻缓冲这一首？

**Comment by lizixian18** [comment]
缓冲是播放器行为，我没办法取消

**Comment by lzkc72** [comment]
这样啊，好吧
