### ISSUE TITLE
Unable to start service Intent 崩溃！

### ISSUE THREAD

**Issue by JeremyHwc** [lizixian18/MusicLibrary#43]
**java.lang.RuntimeException:Unable to create application com.stub.StubApp: java.lang.SecurityException: Unable to start service Intent { com.lzx.musiclibrary.MusicService (has extras) }: Unable to launch app for service Intent {com.lzx.musiclibrary.MusicService }: user 0 is restricted**
2 android.app.ActivityThread.handleBindApplication(ActivityThread.java:4708)
4 Caused by:
5 **java.lang.SecurityException:Unable to start service Intent {com.lzx.musiclibrary.MusicService (has extras) }: Unable to launch app for service Intent {com.lzx.musiclibrary.MusicService }: user 0 is restricted**
6 android.app.ContextImpl.startServiceCommon(ContextImpl.java:1729)
7 android.app.ContextImpl.startService(ContextImpl.java:1702)
8 android.content.ContextWrapper.startService(ContextWrapper.java:494)
9 android.support.v4.content.ContextCompat.startForegroundService(ContextCompat.java)
10 com.lzx.musiclibrary.manager.MusicLibrary.init(MusicLibrary.java)
11 com.lzx.musiclibrary.manager.MusicLibrary.init(MusicLibrary.java)
12 com.meten.meten.app.Configurator.withMusicLibrary(Configurator.java)
13 com.meten.metenenglish.MetenApp.onCreate(MetenApp.java)
14 com.stub.StubApp.onCreate(SourceFile:115)
15 android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
16 android.app.ActivityThread.handleBindApplication(ActivityThread.java:4705)
17 android.app.ActivityThread.access$1500(ActivityThread.java:174)
18 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1458)
19 android.os.Handler.dispatchMessage(Handler.java:110)
20 android.os.Looper.loop(Looper.java:229)
21 android.app.ActivityThread.main(ActivityThread.java:5493)
22 java.lang.reflect.Method.invokeNative(Native Method)
23 java.lang.reflect.Method.invoke(Method.java:515)
24 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
25 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
26 dalvik.system.NativeStart.main(Native Method)

系统版本
Android 4.4.4,level 19

ROM
Oppo/COLOROS

CPU架构
armeabi-v7a

**Comment by lizixian18** [comment]
这貌似是oppo系统的问题

**Comment by JeremyHwc** [comment]
网上查了下，貌似是oppo系统的问题！
