### ISSUE TITLE
设置缓存后出现音频无法播放

### ISSUE THREAD

**Issue by gsy450896356** [lizixian18/MusicLibrary#47]
ExoPlayer error Unable to connect to http://127.0.0.1:40397/http%3A%2F%2Foss.mglmusic.cn%2Faudio%2Fmusic%2F227%2FJFPf5NDmAz.mp3

这是错误信息

**Comment by lizixian18** [comment]
怎么关了，好了吗？

**Comment by gsy450896356** [comment]
是我没有申请读取文件权限导致没法创建缓存目录，已解决，谢谢
