### ISSUE TITLE
“XXX”正在运行，点击了解详情或停止应用

### ISSUE THREAD

**Issue by JeremyHwc** [lizixian18/MusicLibrary#50]
将MusicLibrary集成在项目以后，就会在通知栏显示“XXX”正在运行，点击了解详情或停止应用，这样感觉不太好，这个可以去掉吗。我看qq音乐他们在后台播放的时候，也不会在通知栏显示“QQ音乐”正在运行，点击了解详情或停止应用

**Comment by JeremyHwc** [comment]
android 8.0不允许后台应用创建后台服务，但是一般启动应用的时候进行初始化，5秒内软件肯定已经处于前台了，这个时候系统不会报错。不知道我是不是正解？

**Comment by lizixian18** [comment]
正是这个服务的原因，解决办法找了很久，最后找到了在8.0启动的时候就运行了startForeground这个方法。

**Comment by lizixian18** [comment]
还没找到其他靠谱点的解决方法

**Comment by lizixian18** [comment]
5秒内不调用startForeground会导致ANR，这是8.0服务的一个问题。

**Comment by lizixian18** [comment]
嗯，可以试试
