### ISSUE TITLE
有没有抽取好的音频播放控件 ，因为你的项目无法运行，所以直接来问问

### ISSUE THREAD

**Issue by lmdiloveu** [lizixian18/MusicLibrary#52]
有没有抽取好的音频播放控件，如下图可自行修改布局，但有基本的播放、暂停、显示、隐藏逻辑
![image](https://user-images.githubusercontent.com/8290718/44191261-1750c580-a15d-11e8-917a-cf6c37f0bede.png)

这个控件可同时在多个Activity页面或者frament片段 显示，但是播放的是同一首音频 。
不需要显示播放进度

**Comment by lizixian18** [comment]
无法运行？不会吧

**Comment by lizixian18** [comment]
自己搞一个悬浮窗，布个局，很简单啊

**Comment by lmdiloveu** [comment]
1： 可能是我网络的问题，无法下载gradle吧。
2： 悬浮窗可以考虑，替补方案
3： 你这个库描述有点少，我这种小白可能要花大力气，demo也太复杂。
4： 你这个库是不是可以简单的控制音频播放、暂停、单曲循环播放、随机播放等等功能？

**Comment by lizixian18** [comment]
基本播放功能都没问题，怎么时候我都有写好文档的啊
