### ISSUE TITLE
退出 app 释放播放服务后，重启播放，无法得到 PlayEvent 回调

### ISSUE THREAD

**Issue by windvip** [lizixian18/MusicLibrary#55]
退出 app 时，减少内存占用需要释放播放服务，调用以下方法。此时主进程和音频进程均在。
MusicManager.get().reset();
MusicManager.get().unbindService();

重启启动 app，播放音频，无法得到PlayEvent 的回调。

查看源码看到：
unbindService中调用了解注册回调事件和解绑服务：
    this.control.unregisterPlayerEventListener(this.mOnPlayerEventListener);
    this.control.unregisterTimerTaskListener(this.mOnTimerTaskListener);
    this.mContext.unbindService(this.mServiceConnection);

但是并没有重连和恢复的方法。

建议整理明确：初始化、释放音频、释放后恢复音频、等 API 。
注：释放是为了减少应用退出后内存和 cpu 的占用。考虑释放时是否停止服务。

**Comment by lizixian18** [comment]
https://github.com/lizixian18/MusicLibrary/issues/59

关闭服务对音频进程没影响。新版本会将注册服务交给用户自己，这样可以决定是否开启多进程
