### ISSUE TITLE
android 8.0系统通知栏会提示 “xxx 应用正在后台运行”

### ISSUE THREAD

**Issue by windvip** [lizixian18/MusicLibrary#56]
通知栏会显示一条无法取消的通知：“xx”正在运行 点击即可了解详情或者停止应用

如图
![image](https://user-images.githubusercontent.com/11665737/45549054-fe6d2a00-b858-11e8-9b58-e74d6cc3ceea.png)

**Comment by Jboob** [comment]
服务的问题!

**Comment by windvip** [comment]
@Jboob 8.0 启动服务的方式问题。

**Comment by lizixian18** [comment]
![qq 20181019164141](https://user-images.githubusercontent.com/16240767/47207468-e17ac800-d3bd-11e8-829c-d470b631a298.png)
先这样改

**Comment by pioneerz** [comment]
有好的规避方法嘛，因为前台服务有一定的保活作用，不想使用stopForeground把他去掉，有没有其他的方法规避隐藏掉他？
