### ISSUE TITLE
退出应用调用 reset（非 kill），重启后注册的回调得不到播放状态的通知

### ISSUE THREAD

**Issue by windvip** [lizixian18/MusicLibrary#59]
正常退出app，调用 一下两个 api 释放资源。（进程均存在）
MusicManager.get().reset(); 
MusicManager.get().unbindService();
再次启动后无法得到播放状态的回调。

与楼主沟通，退出时不跳用  MusicManager.get().unbindService(); 但是，系统会自动弹出播放控制的通知栏。

**Comment by lizixian18** [comment]
在新版本这样调用已解决：
```
MusicManager.get().reset();
MusicApplication.getMusicLibrary().stopService();
```
