### ISSUE TITLE
可以播放assets目录下的吗？没有报错日志

### ISSUE THREAD

**Issue by s3hengwu** [lizixian18/MusicLibrary#6]
private void playMusic() {
        SongInfo songInfo = new SongInfo();
        songInfo.setSongId("1000");
        songInfo.setSongName("abc");
        songInfo.setSongUrl("file:///android_asset/voice/1.mp3");
        MusicManager.get().playMusicByInfo(songInfo, false);

    }

**Comment by lizixian18** [comment]
本地文件播放获取Uri的方式是 Uri.fromFile()，但是现在我只有Uri.parse()，是我疏忽了，等我今晚把边播边存的功能提交上去，你明天再更新一下应该就可以了。

**Comment by s3hengwu** [comment]
好的 谢谢

**Comment by lizixian18** [comment]
已经可以了。
