### ISSUE TITLE
传入的音频url直接获取音频时长怎么做

### ISSUE THREAD

**Issue by lkjfyy** [lizixian18/MusicLibrary#63]

**Comment by MrLeion** [comment]
常用的做法一般都是业务服务器或者客户端上传的 CDN直接获取时长的，具体可参考：https://developer.qiniu.com/dora/manual/1247/audio-and-video-metadata-information-avinfo

**Comment by lizixian18** [comment]
可以在回调 void onAsyncLoading(boolean isFinishLoading);  isFinishLoading 为 true 时通过 getDuration() 获取。
