### ISSUE TITLE
BitmapHelper.java:34出现空指针

### ISSUE THREAD

**Issue by 1378282082** [lizixian18/MusicLibrary#66]
java.lang.RuntimeException:An error occured while executing doInBackground()
 android.os.AsyncTask$3.done(AsyncTask.java:304)
 Caused by:
 java.lang.NullPointerException:Attempt to invoke virtual method 'intandroid.graphics.Bitmap.getWidth()' on a null object reference
com.lzx.musiclibrary.helper.BitmapHelper.scaleBitmap(BitmapHelper.java:34)
com.lzx.musiclibrary.utils.AlbumArtCache$BitmapAsyncTask.a(AlbumArtCache.java:101)
com.lzx.musiclibrary.utils.AlbumArtCache$BitmapAsyncTask.doInBackground(AlbumArtCache.java:85)
android.os.AsyncTask$2.call(AsyncTask.java:292)
java.util.concurrent.FutureTask.run(FutureTask.java:237)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)

**Comment by lizixian18** [comment]
已修复
