### ISSUE TITLE
调用stopNotification 后再调用reset 释放播放，会弹出播放控制通知栏

### ISSUE THREAD

**Issue by windvip** [lizixian18/MusicLibrary#70]
MusicManager.get().stopNotification();  之后再 MusicManager.get().reset(); 通知栏会弹出播放操作通知。同时会引出 crash
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.lzx.musiclibrary.aidl.model.SongInfo.getSongCover()' on a null object reference
at com.lzx.musiclibrary.notification.SystemNotification.createNotification(SystemNotification.java:177)

我取消了stopNotification的调用，临时解决了自动弹出播放通知栏的问题。希望从逻辑上根本解决控制栏状态控制问题。

**Comment by lizixian18** [comment]
reset 里面已经包含 stopNotification ，所以不需要再调用 stopNotification
