### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by Dkoran** [lizixian18/MusicLibrary#73]
Can you download and play song in offline mode?
if yes how can you implement that.

**Comment by lizixian18** [comment]
setCacheConfig(cacheConfig) Cache when playing configuration

Example：
CacheConfig cacheConfig = new CacheConfig.Builder()
        .setOpenCacheWhenPlaying(true)
        .setCachePath(CacheUtils.getStorageDirectoryPath() + "/NiceMusic/Cache/")
        .build();

MusicLibrary musicLibrary = new MusicLibrary.Builder(this)
        .setCacheConfig(cacheConfig)
        .build();
musicLibrary.init();
