### ISSUE TITLE
How to update UI

### ISSUE THREAD

**Issue by Dkoran** [lizixian18/MusicLibrary#74]
I wanted to find out how to update my DetailPlayerActivity to get ui change anytime music or song is change from the Notification Control because when I log 
  @Override
    public void onMusicSwitch(SongInfo music) {
       Log.e("Music switch_name","--->" + MusicManager.get().getCurrPlayingIndex() + " --->" + music.getSongName());
       Log.e("Music switch_title",music.getSongName());
}
I don't get anything, Kindly help me fix this bug.
Thank you.

**Comment by lizixian18** [comment]
reference  
https://github.com/lizixian18/NiceMusic/blob/master/app/src/main/java/com/lzx/nicemusic/module/play/PlayingDetailActivity.java

**Comment by Dkoran** [comment]
Please Still it is not working out for me, I will be glad if you can assist me via teamviewer.
thank you

**Comment by lizixian18** [comment]
Please show your code
