### ISSUE TITLE
Notification unbind

### ISSUE THREAD

**Issue by Dkoran** [lizixian18/MusicLibrary#78]
I want to unbind or remove notification from foreground after user clicks on Logout.
I tried this but it is not calling unbind method MusicMaanager.get().unbind but method doesnot exit.

**Comment by mattcianna** [comment]
`    override fun onDestroy() {
        MusicManager.get().stopMusic()
        MusicManager.get().unbindService()
        MusicManager.get().stopNotification()
        super.onDestroy()
    }
`

**Comment by lizixian18** [comment]
Please use the latest version
