### ISSUE TITLE
NotificationCreater

### ISSUE THREAD

**Issue by shenbengit** [lizixian18/MusicLibrary#8]
当我在Application中创建NotificationCreater时后，播放时会报一个错误。请帮忙看一下问题所在。
![tim 20180414231734](https://user-images.githubusercontent.com/24364422/38769742-74c83376-403a-11e8-9326-a4ec75c417f0.png)
![tim 20180414231830](https://user-images.githubusercontent.com/24364422/38769743-74fde66a-403a-11e8-9d4c-01e50e6e1c6b.png)

**Comment by lizixian18** [comment]
收到

**Comment by lizixian18** [comment]
我在demo中按照的的设置运行了一下，没发现什么异常，你可否切到musiclibrary的进程看看输出什么报错日志呢？
![qq 20180415084421](https://user-images.githubusercontent.com/16240767/38773814-5ef81d0a-4089-11e8-87c2-870bfc1e8719.png)

**Comment by shenbengit** [comment]
你好，如果我不创建通知栏的话是可以播放音乐的。同时也在别的项目中测试时，创建通知栏也没有错误，正常运行。有可能是我项目的问题。这是错误log，帮我找下问题，谢谢。
![tim 20180415110455](https://user-images.githubusercontent.com/24364422/38774510-82231712-409d-11e8-9a73-a7e7102a781e.png)
![tim 20180415110537](https://user-images.githubusercontent.com/24364422/38774511-82592d48-409d-11e8-87d0-967f9251e124.png)
![tim 20180415110612](https://user-images.githubusercontent.com/24364422/38774512-82967d1a-409d-11e8-8308-59c944a365ab.png)

**Comment by lizixian18** [comment]
找不到类，你看看你这三个Version分别是多少
![qq 20180415111459](https://user-images.githubusercontent.com/16240767/38774550-59301c14-409e-11e8-9509-4ddc35d8c547.png)

**Comment by shenbengit** [comment]
![1523762658 1](https://user-images.githubusercontent.com/24364422/38774619-c4834062-409f-11e8-9fb5-8525df34cc84.png)

**Comment by lizixian18** [comment]
很奇怪，这样应该有MediaStyle这个类才是，你看看能找到这个类不 ：
```
android.support.v4.media.app.NotificationCompat.MediaStyle
```

如果不行可以考虑用自定义通知栏。

**Comment by shenbengit** [comment]
可以找到 这个类，MusicLibrary我是以module导入的，会不会导致出现找不到这个类的问题。
![1523763311 1](https://user-images.githubusercontent.com/24364422/38774692-5b9cd336-40a1-11e8-91d3-8865e68c3e4c.jpg)

**Comment by lizixian18** [comment]
这我得验证一下才知道，你也可以验证一下看看不用这种方式会怎么样

**Comment by shenbengit** [comment]
还是不行，估计和别的包有冲突。我再试试

**Comment by lizixian18** [comment]
好的，我等会也会验证一下

**Comment by lizixian18** [comment]
老哥，怎么样了，不行的话可以用自定义通知栏，里面没有用到 MediaStyle 的

**Comment by shenbengit** [comment]
不好意思，没看到你的回复，昨天我好像发现和哪个库有冲突了，回去我再验证下。要是的，再告诉你。自定义通知栏是不是还需要在Application创建？
![1523871825 1](https://user-images.githubusercontent.com/24364422/38802016-ecb96f76-419d-11e8-9b31-177267016071.png)
 我写这句话就报错。

**Comment by lizixian18** [comment]
自定义通知栏也是通过在Application创建，一样的，只不过对布局里面控件的 id 和图片资源的命名有一些要求，你可以参考一下 NiceMusic 这个 demo，里面都有的，文档也有写，然后报错的话可以把log也发上来，这样比较好分析问题。

**Comment by shenbengit** [comment]
好的，我测试一下自定义的通知栏。

**Comment by lizixian18** [comment]
我引用了那个库，发现没什么问题，也按照你的配置设置成27，也没发现什么问题。。
![qq 20180417100408](https://user-images.githubusercontent.com/16240767/38844584-b7cfe806-4226-11e8-8e7a-55f6179b9b19.jpg)

我是在 [NiceMusic](https://github.com/lizixian18/NiceMusic) 中做测试的，你也可以用这个demo试试看看....

**Comment by shenbengit** [comment]
很尴尬。。。作为library 导入发下编译后发下，这边报错

![1523941540 1](https://user-images.githubusercontent.com/24364422/38850285-5321588c-4243-11e8-9f06-cb079b074c13.png)，百度后，问题已经解决，缺少android.support.v4.media.app包的问题。可以创建通知栏。

**Comment by lizixian18** [comment]
编译报错？解决就好，有什么问题记得反馈哦

**Comment by shenbengit** [comment]
编译报错，音视频同时播放也完美解决，谢谢大神！！！
