### ISSUE TITLE
MusicManager.get().seekTo(progress);从头播放的问题

### ISSUE THREAD

**Issue by ChiuLui** [lizixian18/MusicLibrary#89]
版本:1.4.5
播放类型:url

//进度条监听
                seekBar.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener() {
                    @Override
                    public void onProgressChanged(SeekBar seekBar, int progress, boolean b) {

                    }

                    @Override
                    public void onStartTrackingTouch(SeekBar seekBar) {

                    }

                    @Override
                    public void onStopTrackingTouch(SeekBar seekBar) {
                        int progress = seekBar.getProgress();
                        //调用了这个之后会重头播放
                        MusicManager.get().seekTo(progress);
                    }
                });

**Comment by EspoirX** [comment]
用新版本试试

**Comment by HQLIE2018** [comment]
旧JAVA版本发生的这个问题要在源码上怎么修改
