### ISSUE TITLE
pausePlayInMillis延迟

### ISSUE THREAD

**Issue by Bruce8hou** [lizixian18/MusicLibrary#90]
pausePlayInMillis在第一次调用的时候可以很精准的停下来，但是下次再调用pausePlayInMillis时候会晚一点时间。和第一次明显有误差（没有具体统计晚的时间，大概200ms的样子），是不是需要做什么清理工作呢？

**Comment by EspoirX** [comment]
pausePlayInMillis 其实就是定时，到点就停掉音乐，如果方法有问题，可以自己实现。
