### ISSUE TITLE
Bus有些问题，以及列表循环只有单曲时不能循环

### ISSUE THREAD

**Issue by cenjunlei** [lizixian18/MusicLibrary#92]
一个是：

1. 

在有封面图的时候，系统通知点击下一首，会报 
java.lang.IllegalArgumentException: method com.lzx.musiclibrary.control.PlayControl.onCurrentQueueIndexUpdated argument 1 has type com.lzx.musiclibrary.bus.tags.QueueIndexUpdated, got com.lzx.musiclibrary.aidl.model.SongInfo 

发现出问题的是PlayQueueManager中
AlbumArtCache.getInstance().fetch(){
....
Bus.getInstance().post(QueueHelper.getMusicInfoById(getSongInfos(), currentPlayingId), BusTags.onMetadataChanged);
...
}  
应该是Bus里同步的问题，改了一下没改成功，临时用下面的方面解决了，可能会漏掉一些事件，望修复一下
public synchronized void post(Object event, String eventTag) {
        PostingThreadState postingState = currentPostingThreadState.get();
//        List<Object> eventQueue = postingState.eventQueue;
        List<Object> eventQueue = new ArrayList<>();
...
}

另外，列表循环只有单曲时不能循环：PlaybackManager中改成这样就好了
public void onPlayCompletion(SongInfo songInfo) {
        if (playMode == PlayMode.PLAY_IN_RANDOM || playMode == PlayMode.PLAY_IN_LIST_LOOP) {
                if (mQueueManager.skipQueuePosition(1, true)) {
                    mCurrentMediaId = "";
                    mPlayback.setCurrentMediaId("");
                    handlePlayRequest();
                }
         }
}

**Comment by EspoirX** [comment]
是的，本来 Bus 是自己模仿 EventBus 简化了一下 ，确实是有点问题，在新版本中已经没用了，你可以试试新版本
