### ISSUE TITLE
监听希望回调出来歌曲信息

### ISSUE THREAD

**Issue by dxsdyhm** [lizixian18/MusicLibrary#96]
```onPlayCompletion```与之前相比少回调了歌曲信息，这个使用起来不是很方便，希望保持以前的格式

**Comment by EspoirX** [comment]
好的，新版本刚弄好不久，现在先主要测测功能有没有bug，API 会尽量跟之前的对齐的。这两天会完善好。

**Comment by dxsdyhm** [comment]
之前的版本，一个音频播完会回调```onplayCompletion```
新版本，一个音频播完只会回调```onplaystop```
* 1.以后一直会这样了么？
* 2.```onPlayCompletion```什么情况下回调？

**Comment by EspoirX** [comment]
已处理，每播完一首歌都会回调 onPlayCompletion(SongInfo songInfo)  参数返回的是上一首歌的信息，注意如果要用到 sonInfo ，保险一点最好判空。
