### ISSUE TITLE
new branch updatePlayList方法更新播放列表问题

### ISSUE THREAD

**Issue by wodaoaicc** [lizixian18/MusicLibrary#99]
MusicProvider类
 //使用Map在查找方面会效率高一点
    private ConcurrentMap<String, SongInfo> mSongInfoListById;
    private ConcurrentMap<String, MediaMetadataCompat> mMusicListById;
这两个数据不同步
 /**
     * 设置播放列表
     */
    public synchronized void setSongInfos(List<SongInfo> songInfos) {
        for (SongInfo info : songInfos) {
            mSongInfoListById.put(info.getSongId(), info);
        }
        mMusicListById = toMediaMetadata(songInfos);
    }
这会导致调用updatePlayList方法后，更新播放列表失败，之后调用播放方法报错
 /**
     * 根据id获取对应的MediaMetadataCompat对象
     */
    public MediaMetadataCompat getMusic(String songId) {
        return mMusicListById.containsKey(songId) ? mMusicListById.get(songId) : null;
    }

**Comment by EspoirX** [comment]
多谢提醒，改为这样应该就可以了：
```
   public synchronized void setSongInfos(List<SongInfo> songInfos) {
        mSongInfoListById.clear();
        for (SongInfo info : songInfos) {
            mSongInfoListById.put(info.getSongId(), info);
        }
        mMusicListById = toMediaMetadata(songInfos);
    }
```
